"""Drop URL columns use media_id

Revision ID: 3191c6895915
Revises: f12c07fc50a7
Create Date: 2026-01-09 04:59:01.359299
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3191c6895915'
down_revision = 'f12c07fc50a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_posts', 'featured_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_posts', sa.Column('featured_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
