"""rename_notification_preferences_member_id_to_member_auth_id_string

Revision ID: 785e73dd9714
Revises: c1f336f3e2dc
Create Date: 2026-05-15 16:24:25.317915
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785e73dd9714'
down_revision = 'c1f336f3e2dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('member_auth_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_notification_preferences_member_id'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_member_auth_id'), 'notification_preferences', ['member_auth_id'], unique=True)
    op.drop_column('notification_preferences', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notification_preferences_member_auth_id'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_member_id'), 'notification_preferences', ['member_id'], unique=True)
    op.drop_column('notification_preferences', 'member_auth_id')
    # ### end Alembic commands ###
