"""add_scheduled_notifications_and_session_notification_logs

Revision ID: 995988fb8afb
Revises: d4ef8535f276
Create Date: 2026-02-09 14:37:05.292174
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995988fb8afb'
down_revision = 'd4ef8535f276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('SESSION_PUBLISHED', 'REMINDER_24H', 'REMINDER_3H', 'REMINDER_1H', 'SESSION_CANCELLED', 'SESSION_UPDATED', 'SPOTS_AVAILABLE', name='session_notification_type_enum'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='scheduled_notification_status_enum'), nullable=False),
    sa.Column('is_short_notice', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_notifications_scheduled_for'), 'scheduled_notifications', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_notifications_session_id'), 'scheduled_notifications', ['session_id'], unique=False)
    op.create_table('session_notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('SESSION_PUBLISHED', 'REMINDER_24H', 'REMINDER_3H', 'REMINDER_1H', 'SESSION_CANCELLED', 'SESSION_UPDATED', 'SPOTS_AVAILABLE', name='session_notification_type_enum'), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_notification_logs_member_id'), 'session_notification_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_session_notification_logs_session_id'), 'session_notification_logs', ['session_id'], unique=False)
    op.add_column('notification_preferences', sa.Column('subscribe_community_sessions', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('subscribe_club_sessions', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('subscribe_event_sessions', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('reminder_24h_enabled', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('reminder_3h_enabled', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('weekly_session_digest', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'weekly_session_digest')
    op.drop_column('notification_preferences', 'reminder_3h_enabled')
    op.drop_column('notification_preferences', 'reminder_24h_enabled')
    op.drop_column('notification_preferences', 'subscribe_event_sessions')
    op.drop_column('notification_preferences', 'subscribe_club_sessions')
    op.drop_column('notification_preferences', 'subscribe_community_sessions')
    op.drop_index(op.f('ix_session_notification_logs_session_id'), table_name='session_notification_logs')
    op.drop_index(op.f('ix_session_notification_logs_member_id'), table_name='session_notification_logs')
    op.drop_table('session_notification_logs')
    op.drop_index(op.f('ix_scheduled_notifications_session_id'), table_name='scheduled_notifications')
    op.drop_index(op.f('ix_scheduled_notifications_scheduled_for'), table_name='scheduled_notifications')
    op.drop_table('scheduled_notifications')
    # ### end Alembic commands ###
