"""add_email_birthday_flag_to_notification_preferences

Revision ID: c1f336f3e2dc
Revises: 23d8ad92dd08
Create Date: 2026-05-02 03:47:01.938105
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f336f3e2dc'
down_revision = '23d8ad92dd08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('email_birthday', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'email_birthday')
    # ### end Alembic commands ###
