"""add_media_id_fields

Revision ID: f12c07fc50a7
Revises: 7d7f2cdc02ab
Create Date: 2026-01-08 06:50:19.153510
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12c07fc50a7'
down_revision = '7d7f2cdc02ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_posts', sa.Column('featured_image_media_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_posts', 'featured_image_media_id')
    # ### end Alembic commands ###
