"""add_approval_and_aboutyou_fields

Revision ID: 43eec681de3c
Revises: f50542311598
Create Date: 2025-12-05 05:19:57.414243
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43eec681de3c"
down_revision = "f50542311598"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "members",
        sa.Column(
            "approval_status", sa.String(), server_default="pending", nullable=False
        ),
    )
    op.add_column("members", sa.Column("approval_notes", sa.String(), nullable=True))
    op.add_column(
        "members", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("members", sa.Column("approved_by", sa.String(), nullable=True))
    op.add_column("members", sa.Column("occupation", sa.String(), nullable=True))
    op.add_column("members", sa.Column("area_in_lagos", sa.String(), nullable=True))
    op.add_column("members", sa.Column("how_found_us", sa.String(), nullable=True))
    op.add_column(
        "members", sa.Column("previous_communities", sa.String(), nullable=True)
    )
    op.add_column(
        "members", sa.Column("hopes_from_swimbuddz", sa.String(), nullable=True)
    )
    op.add_column(
        "members",
        sa.Column(
            "community_rules_accepted",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "community_rules_accepted")
    op.drop_column("members", "hopes_from_swimbuddz")
    op.drop_column("members", "previous_communities")
    op.drop_column("members", "how_found_us")
    op.drop_column("members", "area_in_lagos")
    op.drop_column("members", "occupation")
    op.drop_column("members", "approved_by")
    op.drop_column("members", "approved_at")
    op.drop_column("members", "approval_notes")
    op.drop_column("members", "approval_status")
    # ### end Alembic commands ###
