"""add_requested_tiers

Revision ID: 96a44e71998d
Revises: 43eec681de3c
Create Date: 2025-12-09 01:46:50.648036
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "96a44e71998d"
down_revision = "43eec681de3c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "members",
        sa.Column(
            "requested_membership_tiers", postgresql.ARRAY(sa.String()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "requested_membership_tiers")
    # ### end Alembic commands ###
