"""add coach profile

Revision ID: b2d0f6b1ed51
Revises: 96a44e71998d
Create Date: 2025-12-10 08:35:03.239636
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b2d0f6b1ed51"
down_revision = "96a44e71998d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coach_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("coach_profile_photo_url", sa.String(), nullable=True),
        sa.Column("short_bio", sa.String(), nullable=True),
        sa.Column("full_bio", sa.Text(), nullable=True),
        sa.Column("certifications", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("other_certifications_note", sa.Text(), nullable=True),
        sa.Column("coaching_years", sa.Integer(), server_default="0", nullable=False),
        sa.Column("coaching_experience_summary", sa.Text(), nullable=True),
        sa.Column("coaching_specialties", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("levels_taught", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("age_groups_taught", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "preferred_cohort_types", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("languages_spoken", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("coaching_portfolio_link", sa.String(), nullable=True),
        sa.Column(
            "has_cpr_training", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("cpr_expiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifeguard_expiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "background_check_status",
            sa.String(),
            server_default="not_required",
            nullable=False,
        ),
        sa.Column("background_check_document_url", sa.String(), nullable=True),
        sa.Column(
            "insurance_status", sa.String(), server_default="none", nullable=False
        ),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("pools_supported", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "can_travel_between_pools",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("travel_radius_km", sa.Float(), nullable=True),
        sa.Column(
            "max_swimmers_per_session",
            sa.Integer(),
            server_default="10",
            nullable=False,
        ),
        sa.Column(
            "max_cohorts_at_once", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column(
            "accepts_one_on_one", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "accepts_group_cohorts", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("availability_notes", sa.Text(), nullable=True),
        sa.Column(
            "availability_calendar",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("currency", sa.String(), server_default="NGN", nullable=False),
        sa.Column("one_to_one_rate_per_hour", sa.Integer(), nullable=True),
        sa.Column("group_session_rate_per_hour", sa.Integer(), nullable=True),
        sa.Column("academy_cohort_stipend", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.String(), server_default="pending_review", nullable=False
        ),
        sa.Column(
            "show_in_directory", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("average_rating", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("rating_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coach_profiles")
    # ### end Alembic commands ###
