"""add_referral_model_columns_and_registered_status

Revision ID: 1cc37d30b0f1
Revises: a1b2c3d4e601
Create Date: 2026-02-27 04:45:20.518661
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc37d30b0f1'
down_revision = 'a1b2c3d4e601'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add 'registered' value to referral_status_enum (Alembic doesn't detect enum changes)
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE referral_status_enum ADD VALUE IF NOT EXISTS 'registered'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_codes', sa.Column('successful_referrals', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('referral_codes', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('referral_codes', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('referral_records', sa.Column('referee_registered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('referral_records', sa.Column('qualification_trigger', sa.String(), nullable=True))
    op.add_column('referral_records', sa.Column('referral_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_records', 'referral_code')
    op.drop_column('referral_records', 'qualification_trigger')
    op.drop_column('referral_records', 'referee_registered_at')
    op.drop_column('referral_codes', 'expires_at')
    op.drop_column('referral_codes', 'last_used_at')
    op.drop_column('referral_codes', 'successful_referrals')
    # ### end Alembic commands ###
