"""initial_migration

Revision ID: aca6a1c98788
Revises:
Create Date: 2026-02-19 07:27:26.773544
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aca6a1c98788"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corporate_wallet_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("corporate_wallet_id", sa.UUID(), nullable=False),
        sa.Column("member_wallet_id", sa.UUID(), nullable=False),
        sa.Column("bubbles_allocated", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("added_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corporate_wallet_members_corporate_wallet_id"),
        "corporate_wallet_members",
        ["corporate_wallet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corporate_wallet_members_member_wallet_id"),
        "corporate_wallet_members",
        ["member_wallet_id"],
        unique=False,
    )
    op.create_table(
        "corporate_wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("company_email", sa.String(), nullable=False),
        sa.Column("admin_auth_id", sa.String(), nullable=False),
        sa.Column("budget_total", sa.Integer(), nullable=False),
        sa.Column("budget_remaining", sa.Integer(), nullable=False),
        sa.Column("member_bubble_limit", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "corp_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_corporate_wallets_admin_auth_id"),
        "corporate_wallets",
        ["admin_auth_id"],
        unique=False,
    )
    op.create_table(
        "family_wallet_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_wallet_id", sa.UUID(), nullable=False),
        sa.Column("child_wallet_id", sa.UUID(), nullable=False),
        sa.Column("spending_limit_per_month", sa.Integer(), nullable=True),
        sa.Column("spent_this_month", sa.Integer(), nullable=False),
        sa.Column("month_reset_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "parent_wallet_id != child_wallet_id", name="ck_family_no_self_link"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_wallet_id", "child_wallet_id", name="uq_family_link"
        ),
    )
    op.create_index(
        op.f("ix_family_wallet_links_child_wallet_id"),
        "family_wallet_links",
        ["child_wallet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_wallet_links_parent_wallet_id"),
        "family_wallet_links",
        ["parent_wallet_id"],
        unique=False,
    )
    op.create_table(
        "member_reward_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("member_auth_id", sa.String(), nullable=False),
        sa.Column("reward_rule_id", sa.UUID(), nullable=False),
        sa.Column("wallet_event_id", sa.UUID(), nullable=True),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("bubbles_awarded", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_member_reward_history_member_auth_id"),
        "member_reward_history",
        ["member_auth_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_member_reward_history_reward_rule_id"),
        "member_reward_history",
        ["reward_rule_id"],
        unique=False,
    )
    op.create_table(
        "referral_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("member_auth_id", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("uses_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referral_codes_code"), "referral_codes", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_referral_codes_member_auth_id"),
        "referral_codes",
        ["member_auth_id"],
        unique=True,
    )
    op.create_table(
        "referral_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("referrer_auth_id", sa.String(), nullable=False),
        sa.Column("referee_auth_id", sa.String(), nullable=False),
        sa.Column("referral_code_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUALIFIED",
                "REWARDED",
                "EXPIRED",
                "CANCELLED",
                name="referral_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("referrer_reward_bubbles", sa.Integer(), nullable=True),
        sa.Column("referee_reward_bubbles", sa.Integer(), nullable=True),
        sa.Column("referrer_transaction_id", sa.UUID(), nullable=True),
        sa.Column("referee_transaction_id", sa.UUID(), nullable=True),
        sa.Column("qualified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rewarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referral_records_referee_auth_id"),
        "referral_records",
        ["referee_auth_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_referral_records_referrer_auth_id"),
        "referral_records",
        ["referrer_auth_id"],
        unique=False,
    )
    op.create_table(
        "reward_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column(
            "condition_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("reward_bubbles", sa.Integer(), nullable=False),
        sa.Column("max_grants_per_member", sa.Integer(), nullable=True),
        sa.Column("max_grants_per_period", sa.Integer(), nullable=True),
        sa.Column("period_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reward_rules_event_type"), "reward_rules", ["event_type"], unique=False
    )
    op.create_table(
        "wallet_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "FREEZE",
                "UNFREEZE",
                "SUSPEND",
                "CLOSE",
                "ADMIN_CREDIT",
                "ADMIN_DEBIT",
                "TIER_CHANGE",
                "LIMIT_CHANGE",
                name="audit_action_enum",
            ),
            nullable=False,
        ),
        sa.Column("performed_by", sa.String(), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_audit_logs_wallet_id"),
        "wallet_audit_logs",
        ["wallet_id"],
        unique=False,
    )
    op.create_table(
        "wallet_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("member_auth_id", sa.String(), nullable=False),
        sa.Column("source_service", sa.String(), nullable=False),
        sa.Column(
            "event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_events_event_type"),
        "wallet_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_events_idempotency_key"),
        "wallet_events",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wallet_events_member_auth_id"),
        "wallet_events",
        ["member_auth_id"],
        unique=False,
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("member_auth_id", sa.String(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("lifetime_bubbles_purchased", sa.Integer(), nullable=False),
        sa.Column("lifetime_bubbles_spent", sa.Integer(), nullable=False),
        sa.Column("lifetime_bubbles_received", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "FROZEN", "SUSPENDED", "CLOSED", name="wallet_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("frozen_reason", sa.Text(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("frozen_by", sa.String(), nullable=True),
        sa.Column(
            "wallet_tier",
            sa.Enum("STANDARD", "PREMIUM", "VIP", name="wallet_tier_enum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("balance >= 0", name="ck_wallet_balance_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallets_member_auth_id"), "wallets", ["member_auth_id"], unique=True
    )
    op.create_index(op.f("ix_wallets_member_id"), "wallets", ["member_id"], unique=True)
    op.create_table(
        "promotional_bubble_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("member_auth_id", sa.String(), nullable=False),
        sa.Column(
            "grant_type",
            sa.Enum(
                "WELCOME_BONUS",
                "REFERRAL_REWARD",
                "LOYALTY_REWARD",
                "CAMPAIGN",
                "COMPENSATION",
                "ADMIN_MANUAL",
                "SCHOLARSHIP",
                "DISCOUNT",
                name="grant_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("bubbles_amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("campaign_code", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bubbles_remaining", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("granted_by", sa.String(), nullable=True),
        sa.Column(
            "grant_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("bubbles_amount > 0", name="ck_grant_amount_positive"),
        sa.CheckConstraint(
            "bubbles_remaining <= bubbles_amount", name="ck_grant_remaining_lte_amount"
        ),
        sa.CheckConstraint(
            "bubbles_remaining >= 0", name="ck_grant_remaining_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promotional_bubble_grants_member_auth_id"),
        "promotional_bubble_grants",
        ["member_auth_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promotional_bubble_grants_wallet_id"),
        "promotional_bubble_grants",
        ["wallet_id"],
        unique=False,
    )
    op.create_table(
        "wallet_topups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("member_auth_id", sa.String(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("bubbles_amount", sa.Integer(), nullable=False),
        sa.Column("naira_amount", sa.Integer(), nullable=False),
        sa.Column("exchange_rate", sa.Integer(), nullable=False),
        sa.Column("payment_reference", sa.String(), nullable=True),
        sa.Column(
            "payment_method",
            sa.Enum(
                "PAYSTACK",
                "BANK_TRANSFER",
                "ADMIN_GRANT",
                name="topup_payment_method_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "EXPIRED",
                name="topup_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("paystack_authorization_url", sa.Text(), nullable=True),
        sa.Column("paystack_access_code", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "topup_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("bubbles_amount <= 5000", name="ck_topup_max_bubbles"),
        sa.CheckConstraint("bubbles_amount >= 25", name="ck_topup_min_bubbles"),
        sa.CheckConstraint("naira_amount > 0", name="ck_topup_naira_positive"),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_topups_member_auth_id"),
        "wallet_topups",
        ["member_auth_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_topups_reference"), "wallet_topups", ["reference"], unique=True
    )
    op.create_index(
        op.f("ix_wallet_topups_wallet_id"), "wallet_topups", ["wallet_id"], unique=False
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "TOPUP",
                "PURCHASE",
                "REFUND",
                "WELCOME_BONUS",
                "PROMOTIONAL_CREDIT",
                "REFERRAL_CREDIT",
                "ADMIN_ADJUSTMENT",
                "TRANSFER_IN",
                "TRANSFER_OUT",
                "PENALTY",
                "REWARD",
                "EXPIRY",
                name="transaction_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum("CREDIT", "DEBIT", name="transaction_direction_enum"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance_before", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "FAILED",
                "REVERSED",
                name="transaction_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("service_source", sa.String(), nullable=True),
        sa.Column("reference_type", sa.String(), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("initiated_by", sa.String(), nullable=True),
        sa.Column(
            "txn_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("reversed_by_transaction_id", sa.UUID(), nullable=True),
        sa.Column("reversal_of_transaction_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_transaction_amount_positive"),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_transactions_idempotency_key"),
        "wallet_transactions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        "ix_wallet_transactions_wallet_created",
        "wallet_transactions",
        ["wallet_id", "created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("ix_wallet_transactions_wallet_id"),
        "wallet_transactions",
        ["wallet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wallet_transactions_wallet_id"), table_name="wallet_transactions"
    )
    op.drop_index(
        "ix_wallet_transactions_wallet_created",
        table_name="wallet_transactions",
        postgresql_using="btree",
    )
    op.drop_index(
        op.f("ix_wallet_transactions_idempotency_key"), table_name="wallet_transactions"
    )
    op.drop_table("wallet_transactions")
    op.drop_index(op.f("ix_wallet_topups_wallet_id"), table_name="wallet_topups")
    op.drop_index(op.f("ix_wallet_topups_reference"), table_name="wallet_topups")
    op.drop_index(op.f("ix_wallet_topups_member_auth_id"), table_name="wallet_topups")
    op.drop_table("wallet_topups")
    op.drop_index(
        op.f("ix_promotional_bubble_grants_wallet_id"),
        table_name="promotional_bubble_grants",
    )
    op.drop_index(
        op.f("ix_promotional_bubble_grants_member_auth_id"),
        table_name="promotional_bubble_grants",
    )
    op.drop_table("promotional_bubble_grants")
    op.drop_index(op.f("ix_wallets_member_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_member_auth_id"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_wallet_events_member_auth_id"), table_name="wallet_events")
    op.drop_index(op.f("ix_wallet_events_idempotency_key"), table_name="wallet_events")
    op.drop_index(op.f("ix_wallet_events_event_type"), table_name="wallet_events")
    op.drop_table("wallet_events")
    op.drop_index(
        op.f("ix_wallet_audit_logs_wallet_id"), table_name="wallet_audit_logs"
    )
    op.drop_table("wallet_audit_logs")
    op.drop_index(op.f("ix_reward_rules_event_type"), table_name="reward_rules")
    op.drop_table("reward_rules")
    op.drop_index(
        op.f("ix_referral_records_referrer_auth_id"), table_name="referral_records"
    )
    op.drop_index(
        op.f("ix_referral_records_referee_auth_id"), table_name="referral_records"
    )
    op.drop_table("referral_records")
    op.drop_index(op.f("ix_referral_codes_member_auth_id"), table_name="referral_codes")
    op.drop_index(op.f("ix_referral_codes_code"), table_name="referral_codes")
    op.drop_table("referral_codes")
    op.drop_index(
        op.f("ix_member_reward_history_reward_rule_id"),
        table_name="member_reward_history",
    )
    op.drop_index(
        op.f("ix_member_reward_history_member_auth_id"),
        table_name="member_reward_history",
    )
    op.drop_table("member_reward_history")
    op.drop_index(
        op.f("ix_family_wallet_links_parent_wallet_id"),
        table_name="family_wallet_links",
    )
    op.drop_index(
        op.f("ix_family_wallet_links_child_wallet_id"), table_name="family_wallet_links"
    )
    op.drop_table("family_wallet_links")
    op.drop_index(
        op.f("ix_corporate_wallets_admin_auth_id"), table_name="corporate_wallets"
    )
    op.drop_table("corporate_wallets")
    op.drop_index(
        op.f("ix_corporate_wallet_members_member_wallet_id"),
        table_name="corporate_wallet_members",
    )
    op.drop_index(
        op.f("ix_corporate_wallet_members_corporate_wallet_id"),
        table_name="corporate_wallet_members",
    )
    op.drop_table("corporate_wallet_members")
    # ### end Alembic commands ###
