"""add_wallet_ledger_post_failures

Revision ID: d11870c4f761
Revises: 5db2653c9ce8
Create Date: 2026-06-02 15:13:24.355954
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d11870c4f761"
down_revision = "5db2653c9ce8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_ledger_post_failures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("source_reference", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_ledger_post_failures_idempotency_key"),
        "wallet_ledger_post_failures",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wallet_ledger_post_failures_source_reference"),
        "wallet_ledger_post_failures",
        ["source_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_ledger_post_failures_status"),
        "wallet_ledger_post_failures",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wallet_ledger_post_failures_status"),
        table_name="wallet_ledger_post_failures",
    )
    op.drop_index(
        op.f("ix_wallet_ledger_post_failures_source_reference"),
        table_name="wallet_ledger_post_failures",
    )
    op.drop_index(
        op.f("ix_wallet_ledger_post_failures_idempotency_key"),
        table_name="wallet_ledger_post_failures",
    )
    op.drop_table("wallet_ledger_post_failures")
    # ### end Alembic commands ###
