"""add_coach_context_to_analysis_jobs

Revision ID: 2bd985e3d374
Revises: 5525b0f19fe4
Create Date: 2026-06-21 03:09:06.779742
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd985e3d374'
down_revision = '5525b0f19fe4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swim_analysis_jobs', sa.Column('discipline', sa.String(length=16), server_default='general', nullable=False))
    op.add_column('swim_analysis_jobs', sa.Column('level', sa.String(length=16), nullable=True))
    op.add_column('swim_analysis_jobs', sa.Column('focus_area', sa.String(length=24), nullable=True))
    op.add_column('swim_analysis_jobs', sa.Column('goal_text', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swim_analysis_jobs', 'goal_text')
    op.drop_column('swim_analysis_jobs', 'focus_area')
    op.drop_column('swim_analysis_jobs', 'level')
    op.drop_column('swim_analysis_jobs', 'discipline')
    # ### end Alembic commands ###
