"""add_swim_frame_labels_table

Revision ID: 5525b0f19fe4
Revises: cbd67d9ed87b
Create Date: 2026-06-19 11:46:52.750429
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5525b0f19fe4'
down_revision = 'cbd67d9ed87b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swim_frame_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('arm', sa.String(length=8), server_default='none', nullable=False),
    sa.Column('subphase', sa.String(length=16), server_default='', nullable=False),
    sa.Column('conf', sa.Float(), server_default='0', nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['swim_analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'frame_index', name='uq_frame_label_job_frame')
    )
    op.create_index('ix_frame_label_phase', 'swim_frame_labels', ['phase'], unique=False)
    op.create_index(op.f('ix_swim_frame_labels_job_id'), 'swim_frame_labels', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swim_frame_labels_job_id'), table_name='swim_frame_labels')
    op.drop_index('ix_frame_label_phase', table_name='swim_frame_labels')
    op.drop_table('swim_frame_labels')
    # ### end Alembic commands ###
