"""add strokelab founding members table

Revision ID: 73fc2229b39a
Revises: 9cd30c0c14e0
Create Date: 2026-06-09 22:03:31.278638
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fc2229b39a'
down_revision = '9cd30c0c14e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strokelab_founding_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_auth_id', sa.UUID(), nullable=False),
    sa.Column('paystack_reference', sa.String(length=64), nullable=False),
    sa.Column('amount_paid_kobo', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paystack_reference')
    )
    op.create_index(op.f('ix_strokelab_founding_members_member_auth_id'), 'strokelab_founding_members', ['member_auth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strokelab_founding_members_member_auth_id'), table_name='strokelab_founding_members')
    op.drop_table('strokelab_founding_members')
    # ### end Alembic commands ###
