"""guest_analyzer_jobs_and_analyzer_credits

Revision ID: 9bcbdb5518c4
Revises: 4ea4b98e07f4
Create Date: 2026-06-15 14:04:00.435263

Hand-edited after autogenerate (these cannot be auto-generated):
  * explicit CREATE of analysis_job_source_enum before its add_column
    (op.add_column does not reliably emit CREATE TYPE for a new PG enum,
    unlike create_table);
  * the ck_swim_analysis_jobs_identity CHECK on the EXISTING table
    (autogenerate omits CHECK constraints added to existing tables);
  * the three enum TYPE drops in downgrade() (autogenerate never drops
    Postgres enum types). See docs/design/STROKELAB_PUBLIC_ANALYZER_DESIGN.md §11.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcbdb5518c4'
down_revision = '4ea4b98e07f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzer_credit_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('remaining_credits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_credits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('free_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('lifetime_purchased', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lifetime_spent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('remaining_credits >= 0', name='ck_analyzer_acct_remaining_nonneg'),
    sa.CheckConstraint('reserved_credits >= 0', name='ck_analyzer_acct_reserved_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyzer_credit_accounts_email'), 'analyzer_credit_accounts', ['email'], unique=True)
    op.create_table('analyzer_credit_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('entry_type', sa.Enum('gumroad_grant', 'free_grant', 'reserve', 'consume', 'refund', 'revoke', name='analyzer_credit_entry_enum'), nullable=False),
    sa.Column('direction', sa.Enum('credit', 'debit', name='analyzer_credit_direction_enum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('gumroad_sale_id', sa.String(length=120), nullable=True),
    sa.Column('gumroad_license_key', sa.String(length=120), nullable=True),
    sa.Column('gumroad_permalink', sa.String(length=40), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('reversal_of_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_analyzer_ledger_amount_pos'),
    sa.ForeignKeyConstraint(['account_id'], ['analyzer_credit_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gumroad_sale_id')
    )
    op.create_index(op.f('ix_analyzer_credit_ledger_account_id'), 'analyzer_credit_ledger', ['account_id'], unique=False)
    op.create_index(op.f('ix_analyzer_credit_ledger_email'), 'analyzer_credit_ledger', ['email'], unique=False)
    op.create_index(op.f('ix_analyzer_credit_ledger_idempotency_key'), 'analyzer_credit_ledger', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_analyzer_credit_ledger_job_id'), 'analyzer_credit_ledger', ['job_id'], unique=False)
    op.add_column('swim_analysis_jobs', sa.Column('guest_email', sa.String(length=320), nullable=True))
    op.add_column('swim_analysis_jobs', sa.Column('guest_token', sa.String(length=64), nullable=True))
    # Explicitly create the enum TYPE before the add_column. Unlike create_table,
    # op.add_column does not reliably emit CREATE TYPE for a new PG enum.
    analysis_job_source_enum = sa.Enum('member', 'public', name='analysis_job_source_enum')
    analysis_job_source_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('swim_analysis_jobs', sa.Column('source', sa.Enum('member', 'public', name='analysis_job_source_enum', create_type=False), server_default='member', nullable=False))
    op.add_column('swim_analysis_jobs', sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('swim_analysis_jobs', 'member_auth_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_swim_analysis_jobs_guest_email'), 'swim_analysis_jobs', ['guest_email'], unique=False)
    op.create_index(op.f('ix_swim_analysis_jobs_guest_token'), 'swim_analysis_jobs', ['guest_token'], unique=False)
    # Identity CHECK on the EXISTING table (autogenerate omits CHECKs on existing
    # tables). Safe on current data: every legacy row backfilled to source='member'
    # and already has member_auth_id NOT NULL (the column was NOT NULL until now).
    op.create_check_constraint(
        "ck_swim_analysis_jobs_identity",
        "swim_analysis_jobs",
        "(source = 'member' AND member_auth_id IS NOT NULL) OR "
        "(source = 'public' AND guest_email IS NOT NULL AND guest_token IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the identity CHECK first — it references the source/guest columns.
    op.drop_constraint("ck_swim_analysis_jobs_identity", "swim_analysis_jobs", type_="check")
    op.drop_index(op.f('ix_swim_analysis_jobs_guest_token'), table_name='swim_analysis_jobs')
    op.drop_index(op.f('ix_swim_analysis_jobs_guest_email'), table_name='swim_analysis_jobs')
    op.alter_column('swim_analysis_jobs', 'member_auth_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('swim_analysis_jobs', 'email_sent_at')
    op.drop_column('swim_analysis_jobs', 'source')
    op.drop_column('swim_analysis_jobs', 'guest_token')
    op.drop_column('swim_analysis_jobs', 'guest_email')
    op.drop_index(op.f('ix_analyzer_credit_ledger_job_id'), table_name='analyzer_credit_ledger')
    op.drop_index(op.f('ix_analyzer_credit_ledger_idempotency_key'), table_name='analyzer_credit_ledger')
    op.drop_index(op.f('ix_analyzer_credit_ledger_email'), table_name='analyzer_credit_ledger')
    op.drop_index(op.f('ix_analyzer_credit_ledger_account_id'), table_name='analyzer_credit_ledger')
    op.drop_table('analyzer_credit_ledger')
    op.drop_index(op.f('ix_analyzer_credit_accounts_email'), table_name='analyzer_credit_accounts')
    op.drop_table('analyzer_credit_accounts')
    # Postgres keeps enum TYPEs after their owning columns/tables are dropped;
    # remove ours so a re-upgrade can recreate them.
    sa.Enum(name='analysis_job_source_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analyzer_credit_entry_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analyzer_credit_direction_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
