"""add stroke lab analysis tables

Revision ID: 9cd30c0c14e0
Revises: 3397d7e7699c
Create Date: 2026-06-09 20:33:16.627260
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd30c0c14e0'
down_revision = '3397d7e7699c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swim_analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_auth_id', sa.UUID(), nullable=False),
    sa.Column('stroke_type', sa.String(length=20), nullable=False),
    sa.Column('video_storage_path', sa.Text(), nullable=False),
    sa.Column('annotated_video_storage_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='swim_analysis_job_status_enum'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swim_analysis_jobs_member_auth_id'), 'swim_analysis_jobs', ['member_auth_id'], unique=False)
    op.create_index(op.f('ix_swim_analysis_jobs_status'), 'swim_analysis_jobs', ['status'], unique=False)
    op.create_table('swim_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('detected_stroke', sa.String(length=20), nullable=False),
    sa.Column('pose_detection_rate', sa.Float(), nullable=False),
    sa.Column('frames_total', sa.Integer(), nullable=False),
    sa.Column('frames_with_pose', sa.Integer(), nullable=False),
    sa.Column('stroke_rate_spm', sa.Float(), nullable=True),
    sa.Column('body_roll_proxy_degrees', sa.Float(), nullable=True),
    sa.Column('breath_count_left', sa.Integer(), nullable=True),
    sa.Column('breath_count_right', sa.Integer(), nullable=True),
    sa.Column('breath_balance_left_ratio', sa.Float(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('pipeline_config', sa.JSON(), nullable=True),
    sa.Column('raw_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['swim_analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swim_analysis_results_job_id'), 'swim_analysis_results', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swim_analysis_results_job_id'), table_name='swim_analysis_results')
    op.drop_table('swim_analysis_results')
    op.drop_index(op.f('ix_swim_analysis_jobs_status'), table_name='swim_analysis_jobs')
    op.drop_index(op.f('ix_swim_analysis_jobs_member_auth_id'), table_name='swim_analysis_jobs')
    op.drop_table('swim_analysis_jobs')
    # Postgres keeps enum TYPEs around even after their owning table is
    # dropped; remove ours explicitly so a re-upgrade can recreate it.
    sa.Enum(name='swim_analysis_job_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
