"""B4 audit canonical shape: stage 1 — add new columns (nullable).

Stage 1 of two for chat_audit_log adopting `libs.common.audit.AuditLogMixin`.

Additive only: adds the canonical columns as NULLABLE so existing rows
remain valid. The legacy ``payload`` / ``message_id`` columns and the
``chat_audit_action_enum`` constraint stay in place until stage 2
(``c1a82f4d7a3b_b4_audit_canonical_shape_backfill_and_.py``) has
backfilled the canonical columns and flipped them to NOT NULL.

The original autogenerated body included the destructive operations
(drop payload + message_id, enum→string convert, NOT NULL on new
columns) in this stage. Those were moved to stage 2 so this migration
is a safe rollback boundary: if stage 2 fails, the legacy columns and
the action enum still exist with their data intact.

The new index (``ix_chat_audit_log_entity_created``) IS created here
because it doesn't depend on backfilled data — it sits on the new
``entity_id`` column (nullable for now); it just won't be useful until
stage 2 populates the column. Cheap to add now to avoid a second
schema change later.
"""

revision = 'b0ca76a22b55'
down_revision = '28be07d7e61e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ── Additive canonical columns, all nullable ─────────────────────
    op.add_column(
        'chat_audit_log',
        sa.Column('domain', sa.String(length=32), nullable=True),
    )
    op.add_column(
        'chat_audit_log',
        sa.Column('entity_type', sa.String(length=64), nullable=True),
    )
    op.add_column(
        'chat_audit_log',
        sa.Column('entity_id', sa.UUID(), nullable=True),
    )
    op.add_column(
        'chat_audit_log',
        sa.Column('actor_label', sa.String(length=255), nullable=True),
    )
    op.add_column(
        'chat_audit_log',
        sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        'chat_audit_log',
        sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        'chat_audit_log',
        sa.Column('reason', sa.String(), nullable=True),
    )
    op.add_column(
        'chat_audit_log',
        sa.Column('ip_address', sa.String(length=45), nullable=True),
    )

    # New canonical composite index (cheap to add now).
    op.create_index(
        'ix_chat_audit_log_entity_created',
        'chat_audit_log',
        ['entity_id', 'created_at'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index('ix_chat_audit_log_entity_created', table_name='chat_audit_log')
    op.drop_column('chat_audit_log', 'ip_address')
    op.drop_column('chat_audit_log', 'reason')
    op.drop_column('chat_audit_log', 'new_value')
    op.drop_column('chat_audit_log', 'old_value')
    op.drop_column('chat_audit_log', 'actor_label')
    op.drop_column('chat_audit_log', 'entity_id')
    op.drop_column('chat_audit_log', 'entity_type')
    op.drop_column('chat_audit_log', 'domain')
