"""Sessions Service schemas package."""

from services.sessions_service.schemas.booking import (
    AdminPoolFeeRefundRequest,
    AdminWalkInRequest,
    BookingConfirmRequest,
    BookingGuestCreate,
    BookingGuestResponse,
    BulkBookingItem,
    BulkBookingRequest,
    BulkBookingResponse,
    GuestConvertRequest,
    GuestConvertResponse,
    GuestIntent,
    GuestLeadResponse,
    RunningLateRequest,
    SessionBookingCreate,
    SessionBookingResponse,
    TrialGuestCreate,
    UnpaidBookingResponse,
)
from services.sessions_service.schemas.main import (
    SessionBase,
    SessionCreate,
    SessionResponse,
    SessionUpdate,
)
from services.sessions_service.schemas.makeup import (
    BookableSlotResponse,
    BookableSlotsResponse,
    MakeupBookingCreate,
    MakeupBookingResponse,
    MakeupOpenSlotCreate,
    MakeupRequestCreate,
)
from services.sessions_service.schemas.templates import (
    GenerateSessionsRequest,
    SessionTemplateBase,
    SessionTemplateCreate,
    SessionTemplateResponse,
    SessionTemplateUpdate,
)

__all__ = [
    "AdminPoolFeeRefundRequest",
    "AdminWalkInRequest",
    "BookableSlotResponse",
    "BookableSlotsResponse",
    "BookingConfirmRequest",
    "BookingGuestCreate",
    "BookingGuestResponse",
    "BulkBookingItem",
    "BulkBookingRequest",
    "BulkBookingResponse",
    "GenerateSessionsRequest",
    "GuestConvertRequest",
    "GuestConvertResponse",
    "GuestIntent",
    "GuestLeadResponse",
    "MakeupBookingCreate",
    "MakeupBookingResponse",
    "MakeupOpenSlotCreate",
    "MakeupRequestCreate",
    "RunningLateRequest",
    "SessionBase",
    "SessionBookingCreate",
    "SessionBookingResponse",
    "TrialGuestCreate",
    "SessionCreate",
    "SessionResponse",
    "SessionTemplateBase",
    "SessionTemplateCreate",
    "SessionTemplateResponse",
    "SessionTemplateUpdate",
    "SessionUpdate",
    "UnpaidBookingResponse",
]
