"""add_pool_hours_first_timer_percentile_session_highlights_community_milestones

Revision ID: 039dbdc232fe
Revises: 76eecf611590
Create Date: 2026-03-26 20:40:55.682566
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '039dbdc232fe'
down_revision = '76eecf611590'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_quarterly_stats', sa.Column('total_pool_hours', sa.Float(), nullable=False, server_default='0'))
    op.add_column('community_quarterly_stats', sa.Column('most_active_location', sa.String(), nullable=True))
    op.add_column('community_quarterly_stats', sa.Column('busiest_session_title', sa.String(), nullable=True))
    op.add_column('community_quarterly_stats', sa.Column('busiest_session_attendance', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('community_quarterly_stats', sa.Column('most_popular_day', sa.String(), nullable=True))
    op.add_column('community_quarterly_stats', sa.Column('most_popular_time_slot', sa.String(), nullable=True))
    op.add_column('community_quarterly_stats', sa.Column('total_cohorts_completed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('member_quarterly_reports', sa.Column('pool_hours', sa.Float(), nullable=False, server_default='0'))
    op.add_column('member_quarterly_reports', sa.Column('is_first_quarter', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('member_quarterly_reports', sa.Column('member_joined_at', sa.String(), nullable=True))
    op.add_column('member_quarterly_reports', sa.Column('attendance_percentile', sa.Float(), nullable=False, server_default='0'))
    op.add_column('member_quarterly_reports', sa.Column('academy_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('member_quarterly_reports', sa.Column('cohorts_completed', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_quarterly_reports', 'cohorts_completed')
    op.drop_column('member_quarterly_reports', 'academy_skills')
    op.drop_column('member_quarterly_reports', 'attendance_percentile')
    op.drop_column('member_quarterly_reports', 'member_joined_at')
    op.drop_column('member_quarterly_reports', 'is_first_quarter')
    op.drop_column('member_quarterly_reports', 'pool_hours')
    op.drop_column('community_quarterly_stats', 'total_cohorts_completed')
    op.drop_column('community_quarterly_stats', 'most_popular_time_slot')
    op.drop_column('community_quarterly_stats', 'most_popular_day')
    op.drop_column('community_quarterly_stats', 'busiest_session_attendance')
    op.drop_column('community_quarterly_stats', 'busiest_session_title')
    op.drop_column('community_quarterly_stats', 'most_active_location')
    op.drop_column('community_quarterly_stats', 'total_pool_hours')
    # ### end Alembic commands ###
