"""add_seasonality_tables

Revision ID: 76eecf611590
Revises: 836ad6a35d0c
Create Date: 2026-03-26 12:13:56.296470
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76eecf611590'
down_revision = '836ad6a35d0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('rainfall_category', sa.String(), nullable=False),
    sa.Column('school_term_active', sa.Boolean(), nullable=False),
    sa.Column('exam_period', sa.Boolean(), nullable=False),
    sa.Column('school_holiday', sa.Boolean(), nullable=False),
    sa.Column('holiday_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('holiday_count', sa.Integer(), nullable=False),
    sa.Column('salary_week', sa.Boolean(), nullable=False),
    sa.Column('campaign_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('campaign_effect_multiplier', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('system', 'manual', 'import', 'prior', name='data_source_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_external_factor_year_month')
    )
    op.create_table('monthly_actuals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('active_members', sa.Integer(), nullable=False),
    sa.Column('total_sessions_held', sa.Integer(), nullable=False),
    sa.Column('total_attendance', sa.Integer(), nullable=False),
    sa.Column('new_signups', sa.Integer(), nullable=False),
    sa.Column('churned_members', sa.Integer(), nullable=False),
    sa.Column('total_revenue_ngn', sa.Integer(), nullable=False),
    sa.Column('attendance_by_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_by_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('is_school_term', sa.Boolean(), nullable=False),
    sa.Column('is_exam_period', sa.Boolean(), nullable=False),
    sa.Column('holiday_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('system', 'manual', 'import', 'prior', name='data_source_enum'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_monthly_actual_year_month')
    )
    op.create_table('seasonality_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_year', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='forecast_status_enum'), nullable=False),
    sa.Column('model_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('monthly_forecasts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('months_of_real_data', sa.Integer(), nullable=False),
    sa.Column('prior_weight', sa.Float(), nullable=False),
    sa.Column('markdown_path', sa.String(), nullable=True),
    sa.Column('csv_path', sa.String(), nullable=True),
    sa.Column('html_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasonality_forecasts_forecast_year'), 'seasonality_forecasts', ['forecast_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seasonality_forecasts_forecast_year'), table_name='seasonality_forecasts')
    op.drop_table('seasonality_forecasts')
    op.drop_table('monthly_actuals')
    op.drop_table('external_factors')
    # ### end Alembic commands ###
