"""initial_migration

Revision ID: 9f18e12b9885
Revises: 
Create Date: 2025-11-30 23:34:13.863906
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f18e12b9885'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', 'CANCELLED', name='attendance_status_enum'), nullable=False),
    sa.Column('role', sa.Enum('SWIMMER', 'COACH', 'VOLUNTEER', 'GUEST', name='attendance_role_enum'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'member_id', name='uq_session_member_attendance')
    )
    op.create_index(op.f('ix_attendance_records_member_id'), 'attendance_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_member_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
