"""add_booking_guest_id_to_attendance_records_for_guest_attendance

Revision ID: b5696faef891
Revises: eef1a39ff17f
Create Date: 2026-06-10 16:47:32.890693
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5696faef891'
down_revision = 'eef1a39ff17f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('booking_guest_id', sa.UUID(), nullable=True))
    op.alter_column('attendance_records', 'member_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_attendance_records_booking_guest_id'), 'attendance_records', ['booking_guest_id'], unique=False)
    op.create_unique_constraint('uq_session_booking_guest_attendance', 'attendance_records', ['session_id', 'booking_guest_id'])
    # Alembic autogenerate cannot represent a CHECK on an existing table — add
    # it explicitly so the DB matches the model (ck_attendance_member_xor_guest).
    op.create_check_constraint(
        'ck_attendance_member_xor_guest',
        'attendance_records',
        '(member_id IS NOT NULL) <> (booking_guest_id IS NOT NULL)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_attendance_member_xor_guest', 'attendance_records', type_='check')
    op.drop_constraint('uq_session_booking_guest_attendance', 'attendance_records', type_='unique')
    op.drop_index(op.f('ix_attendance_records_booking_guest_id'), table_name='attendance_records')
    op.alter_column('attendance_records', 'member_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('attendance_records', 'booking_guest_id')
    # ### end Alembic commands ###
