"""add_booking_id_plain_uuid_for_crossservice_ref

Revision ID: eef1a39ff17f
Revises: 6e7acedd3c03
Create Date: 2026-05-17 09:50:45.466538
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef1a39ff17f'
down_revision = '6e7acedd3c03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('booking_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_attendance_records_booking_id'), 'attendance_records', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_booking_id'), table_name='attendance_records')
    op.drop_column('attendance_records', 'booking_id')
    # ### end Alembic commands ###
