"""add_member_profile_columns

Revision ID: 35100a7c1b2d
Revises: b58e54d8377b
Create Date: 2025-11-20 11:11:45.821267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35100a7c1b2d'
down_revision: Union[str, Sequence[str], None] = 'b58e54d8377b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('members', sa.Column('city', sa.String(), nullable=True))
    op.add_column('members', sa.Column('country', sa.String(), nullable=True))
    op.add_column('members', sa.Column('time_zone', sa.String(), nullable=True))
    op.add_column('members', sa.Column('swim_level', sa.String(), nullable=True))
    op.add_column('members', sa.Column('deep_water_comfort', sa.String(), nullable=True))
    op.add_column('members', sa.Column('strokes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('goals_narrative', sa.String(), nullable=True))
    op.add_column('members', sa.Column('goals_other', sa.String(), nullable=True))
    op.add_column('members', sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('coaching_experience', sa.String(), nullable=True))
    op.add_column('members', sa.Column('coaching_specialties', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('coaching_years', sa.String(), nullable=True))
    op.add_column('members', sa.Column('coaching_portfolio_link', sa.String(), nullable=True))
    op.add_column('members', sa.Column('coaching_document_link', sa.String(), nullable=True))
    op.add_column('members', sa.Column('coaching_document_file_name', sa.String(), nullable=True))
    op.add_column('members', sa.Column('availability_slots', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('time_of_day_availability', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('location_preference', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('location_preference_other', sa.String(), nullable=True))
    op.add_column('members', sa.Column('travel_flexibility', sa.String(), nullable=True))
    op.add_column('members', sa.Column('facility_access', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('facility_access_other', sa.String(), nullable=True))
    op.add_column('members', sa.Column('equipment_needs', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('equipment_needs_other', sa.String(), nullable=True))
    op.add_column('members', sa.Column('travel_notes', sa.String(), nullable=True))
    op.add_column('members', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('members', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    op.add_column('members', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('members', sa.Column('emergency_contact_region', sa.String(), nullable=True))
    op.add_column('members', sa.Column('medical_info', sa.String(), nullable=True))
    op.add_column('members', sa.Column('safety_notes', sa.String(), nullable=True))
    op.add_column('members', sa.Column('volunteer_interest', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('volunteer_roles_detail', sa.String(), nullable=True))
    op.add_column('members', sa.Column('discovery_source', sa.String(), nullable=True))
    op.add_column('members', sa.Column('social_instagram', sa.String(), nullable=True))
    op.add_column('members', sa.Column('social_linkedin', sa.String(), nullable=True))
    op.add_column('members', sa.Column('social_other', sa.String(), nullable=True))
    op.add_column('members', sa.Column('language_preference', sa.String(), nullable=True))
    op.add_column('members', sa.Column('comms_preference', sa.String(), nullable=True))
    op.add_column('members', sa.Column('payment_readiness', sa.String(), nullable=True))
    op.add_column('members', sa.Column('currency_preference', sa.String(), nullable=True))
    op.add_column('members', sa.Column('consent_photo', sa.String(), nullable=True))
    op.add_column('members', sa.Column('membership_tiers', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('academy_focus_areas', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('members', sa.Column('academy_focus', sa.String(), nullable=True))
    op.add_column('members', sa.Column('payment_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'payment_notes')
    op.drop_column('members', 'academy_focus')
    op.drop_column('members', 'academy_focus_areas')
    op.drop_column('members', 'membership_tiers')
    op.drop_column('members', 'consent_photo')
    op.drop_column('members', 'currency_preference')
    op.drop_column('members', 'payment_readiness')
    op.drop_column('members', 'comms_preference')
    op.drop_column('members', 'language_preference')
    op.drop_column('members', 'social_other')
    op.drop_column('members', 'social_linkedin')
    op.drop_column('members', 'social_instagram')
    op.drop_column('members', 'discovery_source')
    op.drop_column('members', 'volunteer_roles_detail')
    op.drop_column('members', 'volunteer_interest')
    op.drop_column('members', 'safety_notes')
    op.drop_column('members', 'medical_info')
    op.drop_column('members', 'emergency_contact_region')
    op.drop_column('members', 'emergency_contact_phone')
    op.drop_column('members', 'emergency_contact_relationship')
    op.drop_column('members', 'emergency_contact_name')
    op.drop_column('members', 'travel_notes')
    op.drop_column('members', 'equipment_needs_other')
    op.drop_column('members', 'equipment_needs')
    op.drop_column('members', 'facility_access_other')
    op.drop_column('members', 'facility_access')
    op.drop_column('members', 'travel_flexibility')
    op.drop_column('members', 'location_preference_other')
    op.drop_column('members', 'location_preference')
    op.drop_column('members', 'time_of_day_availability')
    op.drop_column('members', 'availability_slots')
    op.drop_column('members', 'coaching_document_file_name')
    op.drop_column('members', 'coaching_document_link')
    op.drop_column('members', 'coaching_portfolio_link')
    op.drop_column('members', 'coaching_years')
    op.drop_column('members', 'coaching_specialties')
    op.drop_column('members', 'coaching_experience')
    op.drop_column('members', 'certifications')
    op.drop_column('members', 'goals_other')
    op.drop_column('members', 'goals_narrative')
    op.drop_column('members', 'interests')
    op.drop_column('members', 'strokes')
    op.drop_column('members', 'deep_water_comfort')
    op.drop_column('members', 'swim_level')
    op.drop_column('members', 'time_zone')
    op.drop_column('members', 'country')
    op.drop_column('members', 'city')
    op.drop_column('members', 'phone')
    # ### end Alembic commands ###
