"""add_ride_share_option

Revision ID: 8992845f9a9d
Revises: 35100a7c1b2d
Create Date: 2025-11-20 22:52:07.180521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8992845f9a9d'
down_revision: Union[str, Sequence[str], None] = '35100a7c1b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type manually
    ride_share_option_enum = sa.Enum('NONE', 'LEAD', 'JOIN', name='ride_share_option_enum')
    ride_share_option_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('session_attendance', sa.Column('ride_share_option', ride_share_option_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_attendance', 'ride_share_option')
    
    # Drop the enum type
    ride_share_option_enum = sa.Enum('NONE', 'LEAD', 'JOIN', name='ride_share_option_enum')
    ride_share_option_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
