"""add_attendance

Revision ID: a91a5b70ad47
Revises: b9bb8441004b
Create Date: 2025-11-19 17:56:29.129497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91a5b70ad47'
down_revision: Union[str, Sequence[str], None] = 'b9bb8441004b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('needs_ride', sa.Boolean(), nullable=False),
    sa.Column('can_offer_ride', sa.Boolean(), nullable=False),
    sa.Column('ride_notes', sa.String(), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'WAIVED', 'FAILED', name='payment_status_enum'), nullable=False),
    sa.Column('total_fee', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'member_id', name='uq_session_member_attendance')
    )
    op.create_index(op.f('ix_session_attendance_member_id'), 'session_attendance', ['member_id'], unique=False)
    op.create_index(op.f('ix_session_attendance_session_id'), 'session_attendance', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_attendance_session_id'), table_name='session_attendance')
    op.drop_index(op.f('ix_session_attendance_member_id'), table_name='session_attendance')
    op.drop_table('session_attendance')
    # ### end Alembic commands ###
