"""add pickup_location

Revision ID: acce2ce071fe
Revises: 8992845f9a9d
Create Date: 2025-11-21 06:08:59.127923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acce2ce071fe'
down_revision: Union[str, Sequence[str], None] = '8992845f9a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_attendance', sa.Column('pickup_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_attendance', 'pickup_location')
    # ### end Alembic commands ###
