"""add_revenue_recognition_schedules

Revision ID: b7cd6226722a
Revises: 298d02a91299
Create Date: 2026-06-02 03:11:33.625634
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cd6226722a'
down_revision = '298d02a91299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_recognition_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source_service', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('origin_entry_id', sa.UUID(), nullable=True),
    sa.Column('deferred_account_ref', sa.String(), nullable=False),
    sa.Column('revenue_account_ref', sa.String(), nullable=False),
    sa.Column('dimension_1', sa.String(), nullable=True),
    sa.Column('member_ref', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('recognized_minor', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.Enum('straight_line', name='ledger_recognition_method_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='ledger_recognition_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['ledger_organizations.id'], ),
    sa.ForeignKeyConstraint(['origin_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'source_service', 'source_type', 'source_id', 'deferred_account_ref', name='uq_recognition_schedule_source')
    )
    op.create_index(op.f('ix_revenue_recognition_schedules_org_id'), 'revenue_recognition_schedules', ['org_id'], unique=False)
    op.create_index(op.f('ix_revenue_recognition_schedules_status'), 'revenue_recognition_schedules', ['status'], unique=False)
    # NOTE: autogenerate also emitted a drop of `ix_chart_of_accounts_maps_to`
    # (a functional index on account_metadata->>'maps_to' created in 298d02a91299).
    # That's a false positive — the index isn't declared in the model so alembic
    # can't match it — and the index is load-bearing for account-ref resolution.
    # Deliberately removed so this migration only creates the recognition table.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_recognition_schedules_status'), table_name='revenue_recognition_schedules')
    op.drop_index(op.f('ix_revenue_recognition_schedules_org_id'), table_name='revenue_recognition_schedules')
    op.drop_table('revenue_recognition_schedules')
    # ### end Alembic commands ###
