"""add_reconciliation_tables

Revision ID: de1babbc521e
Revises: b7cd6226722a
Create Date: 2026-06-02 11:20:50.774079
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de1babbc521e'
down_revision = 'b7cd6226722a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('psp', sa.String(), nullable=False),
    sa.Column('external_txn_id', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('settlement_ref', sa.String(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_status', sa.String(), nullable=False),
    sa.Column('matched_entry_id', sa.UUID(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['ledger_organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'psp', 'external_txn_id', name='uq_external_txn_id')
    )
    op.create_index(op.f('ix_external_transactions_external_ref'), 'external_transactions', ['external_ref'], unique=False)
    op.create_index(op.f('ix_external_transactions_match_status'), 'external_transactions', ['match_status'], unique=False)
    op.create_index(op.f('ix_external_transactions_org_id'), 'external_transactions', ['org_id'], unique=False)
    op.create_index(op.f('ix_external_transactions_settlement_ref'), 'external_transactions', ['settlement_ref'], unique=False)
    op.create_table('reconciliation_breaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('break_type', sa.String(), nullable=False),
    sa.Column('psp', sa.String(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('external_txn_id', sa.String(), nullable=True),
    sa.Column('settlement_ref', sa.String(), nullable=True),
    sa.Column('expected_minor', sa.BigInteger(), nullable=True),
    sa.Column('actual_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['ledger_organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'break_type', 'external_ref', name='uq_recon_break')
    )
    op.create_index(op.f('ix_reconciliation_breaks_break_type'), 'reconciliation_breaks', ['break_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_breaks_external_ref'), 'reconciliation_breaks', ['external_ref'], unique=False)
    op.create_index(op.f('ix_reconciliation_breaks_org_id'), 'reconciliation_breaks', ['org_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_breaks_status'), 'reconciliation_breaks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_breaks_status'), table_name='reconciliation_breaks')
    op.drop_index(op.f('ix_reconciliation_breaks_org_id'), table_name='reconciliation_breaks')
    op.drop_index(op.f('ix_reconciliation_breaks_external_ref'), table_name='reconciliation_breaks')
    op.drop_index(op.f('ix_reconciliation_breaks_break_type'), table_name='reconciliation_breaks')
    op.drop_table('reconciliation_breaks')
    op.drop_index(op.f('ix_external_transactions_settlement_ref'), table_name='external_transactions')
    op.drop_index(op.f('ix_external_transactions_org_id'), table_name='external_transactions')
    op.drop_index(op.f('ix_external_transactions_match_status'), table_name='external_transactions')
    op.drop_index(op.f('ix_external_transactions_external_ref'), table_name='external_transactions')
    op.drop_table('external_transactions')
    # ### end Alembic commands ###
