"""add_swim_assessments_table

Revision ID: 2c6622e2de07
Revises: a1b2c3d4e5f6
Create Date: 2026-03-09 04:07:31.623073
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c6622e2de07'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swim_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swim_assessments_level'), 'swim_assessments', ['level'], unique=False)
    op.create_index(op.f('ix_swim_assessments_member_id'), 'swim_assessments', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swim_assessments_member_id'), table_name='swim_assessments')
    op.drop_index(op.f('ix_swim_assessments_level'), table_name='swim_assessments')
    op.drop_table('swim_assessments')
    # ### end Alembic commands ###
