"""challenge_revamp_phase1

Phase 1 of the challenges revamp. Adds:
  * 4 new tables: challenge_example_media, challenge_submission_media,
    challenge_submission_members, challenge_badge_awards
  * Many columns on club_challenges (audience/format/scoping/rewards/team
    config/visibility/schedule)
  * Submission lifecycle columns on member_challenge_completions
    (status, reviewed_at, reviewed_by, review_note, submission_note,
    is_team_submission, submitted_by_member_id, rewards_distributed_at)

Revision ID: 57343c61d16e
Revises: c4f2a1b9d8e3
Create Date: 2026-05-06 12:54:15.234073
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57343c61d16e'
down_revision = 'c4f2a1b9d8e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_badge_awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('badge_image_media_id', sa.UUID(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['member_challenge_completions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'challenge_id', name='uq_badge_member_challenge')
    )
    op.create_index(op.f('ix_challenge_badge_awards_challenge_id'), 'challenge_badge_awards', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_badge_awards_member_id'), 'challenge_badge_awards', ['member_id'], unique=False)
    op.create_table('challenge_example_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('order_idx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['club_challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_example_media_challenge_id'), 'challenge_example_media', ['challenge_id'], unique=False)
    op.create_table('challenge_submission_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('order_idx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['member_challenge_completions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_submission_media_submission_id'), 'challenge_submission_media', ['submission_id'], unique=False)
    op.create_table('challenge_submission_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('badge_awarded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('bubbles_grant_id', sa.UUID(), nullable=True),
    sa.Column('volunteer_hours_log_id', sa.UUID(), nullable=True),
    sa.Column('rewarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['member_challenge_completions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'member_id', name='uq_submission_member')
    )
    op.create_index(op.f('ix_challenge_submission_members_member_id'), 'challenge_submission_members', ['member_id'], unique=False)
    op.create_index(op.f('ix_challenge_submission_members_submission_id'), 'challenge_submission_members', ['submission_id'], unique=False)
    # NOTE: alembic autogen also detected unrelated drift on
    # agreement_versions (a stale model vs the live DB). Those ops were
    # removed from this migration to keep its scope to the challenges
    # revamp; they will reappear in the next migration that touches
    # the coach agreement system.
    op.add_column('club_challenges', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('club_challenges', sa.Column('reward_badge_image_media_id', sa.UUID(), nullable=True))
    op.add_column('club_challenges', sa.Column('reward_bubbles_amount', sa.Integer(), nullable=True))
    op.add_column('club_challenges', sa.Column('reward_volunteer_hours', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('club_challenges', sa.Column('audience', sa.String(), server_default='all', nullable=False))
    op.add_column('club_challenges', sa.Column('club_id', sa.UUID(), nullable=True))
    op.add_column('club_challenges', sa.Column('academy_cohort_id', sa.UUID(), nullable=True))
    op.add_column('club_challenges', sa.Column('format', sa.String(), server_default='participatory', nullable=False))
    op.add_column('club_challenges', sa.Column('winner_submission_id', sa.UUID(), nullable=True))
    op.add_column('club_challenges', sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('club_challenges', sa.Column('show_winner_media_publicly', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('club_challenges', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('club_challenges', sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('club_challenges', sa.Column('team_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('club_challenges', sa.Column('team_min_size', sa.SmallInteger(), nullable=True))
    op.add_column('club_challenges', sa.Column('team_max_size', sa.SmallInteger(), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('submitted_by_member_id', sa.UUID(), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('submission_note', sa.Text(), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('is_team_submission', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('member_challenge_completions', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    op.add_column('member_challenge_completions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('review_note', sa.Text(), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('rewards_distributed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_challenge_completions', 'rewards_distributed_at')
    op.drop_column('member_challenge_completions', 'review_note')
    op.drop_column('member_challenge_completions', 'reviewed_by')
    op.drop_column('member_challenge_completions', 'reviewed_at')
    op.drop_column('member_challenge_completions', 'status')
    op.drop_column('member_challenge_completions', 'is_team_submission')
    op.drop_column('member_challenge_completions', 'submission_note')
    op.drop_column('member_challenge_completions', 'submitted_by_member_id')
    op.drop_column('club_challenges', 'team_max_size')
    op.drop_column('club_challenges', 'team_min_size')
    op.drop_column('club_challenges', 'team_enabled')
    op.drop_column('club_challenges', 'ends_at')
    op.drop_column('club_challenges', 'starts_at')
    op.drop_column('club_challenges', 'show_winner_media_publicly')
    op.drop_column('club_challenges', 'is_public')
    op.drop_column('club_challenges', 'winner_submission_id')
    op.drop_column('club_challenges', 'format')
    op.drop_column('club_challenges', 'academy_cohort_id')
    op.drop_column('club_challenges', 'club_id')
    op.drop_column('club_challenges', 'audience')
    op.drop_column('club_challenges', 'reward_volunteer_hours')
    op.drop_column('club_challenges', 'reward_bubbles_amount')
    op.drop_column('club_challenges', 'reward_badge_image_media_id')
    op.drop_column('club_challenges', 'instructions')
    # (agreement_versions ops intentionally removed; see note in upgrade())
    op.drop_index(op.f('ix_challenge_submission_members_submission_id'), table_name='challenge_submission_members')
    op.drop_index(op.f('ix_challenge_submission_members_member_id'), table_name='challenge_submission_members')
    op.drop_table('challenge_submission_members')
    op.drop_index(op.f('ix_challenge_submission_media_submission_id'), table_name='challenge_submission_media')
    op.drop_table('challenge_submission_media')
    op.drop_index(op.f('ix_challenge_example_media_challenge_id'), table_name='challenge_example_media')
    op.drop_table('challenge_example_media')
    op.drop_index(op.f('ix_challenge_badge_awards_member_id'), table_name='challenge_badge_awards')
    op.drop_index(op.f('ix_challenge_badge_awards_challenge_id'), table_name='challenge_badge_awards')
    op.drop_table('challenge_badge_awards')
    # ### end Alembic commands ###
