"""add_coach_min_hours_between_sessions

Revision ID: 5e7751f89eaf
Revises: e9b575bf1e25
Create Date: 2026-06-03 10:39:17.159644
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7751f89eaf'
down_revision = 'e9b575bf1e25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_profiles', sa.Column('min_hours_between_sessions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_profiles', 'min_hours_between_sessions')
    # ### end Alembic commands ###
