"""Drop URL columns use media_id

Revision ID: 6be39f69482b
Revises: e415f49f60c3
Create Date: 2026-01-09 04:57:07.934230
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be39f69482b'
down_revision = 'e415f49f60c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
