"""add_guardian_links_table_for_minorguardian_relationships

Revision ID: 7b25b3b337ee
Revises: 2c6622e2de07
Create Date: 2026-04-20 02:35:33.747851
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b25b3b337ee'
down_revision = '2c6622e2de07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('minor_member_id', sa.UUID(), nullable=False),
    sa.Column('guardian_member_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.Enum('parent', 'legal_guardian', 'grandparent', 'other_adult', name='guardian_relationship_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('minor_member_id <> guardian_member_id', name='ck_guardian_link_distinct_members'),
    sa.ForeignKeyConstraint(['guardian_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['minor_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_links_guardian_member_id'), 'guardian_links', ['guardian_member_id'], unique=False)
    op.create_index(op.f('ix_guardian_links_minor_member_id'), 'guardian_links', ['minor_member_id'], unique=False)
    op.create_index('uq_guardian_link_active_pair', 'guardian_links', ['minor_member_id', 'guardian_member_id'], unique=True, postgresql_where='is_active = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_guardian_link_active_pair', table_name='guardian_links', postgresql_where='is_active = true')
    op.drop_index(op.f('ix_guardian_links_minor_member_id'), table_name='guardian_links')
    op.drop_index(op.f('ix_guardian_links_guardian_member_id'), table_name='guardian_links')
    op.drop_table('guardian_links')
    # ### end Alembic commands ###
