"""add roles and coach application fields

Revision ID: 7ee75227c5ec
Revises: a6ac42c5717f
Create Date: 2025-12-24 20:49:34.579219
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ee75227c5ec'
down_revision = 'a6ac42c5717f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("SET LOCAL statement_timeout = 0"))
    op.add_column('coach_profiles', sa.Column('application_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coach_profiles', sa.Column('application_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coach_profiles', sa.Column('application_reviewed_by', sa.String(), nullable=True))
    op.add_column('coach_profiles', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # Add without default/not-null first to avoid table rewrite, then backfill in-place.
    op.add_column('members', sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True))
    op.execute(sa.text("UPDATE members SET roles = ARRAY['member'] WHERE roles IS NULL"))
    op.alter_column(
        'members',
        'roles',
        server_default=sa.text("'{member}'"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'roles')
    op.drop_column('coach_profiles', 'rejection_reason')
    op.drop_column('coach_profiles', 'application_reviewed_by')
    op.drop_column('coach_profiles', 'application_reviewed_at')
    op.drop_column('coach_profiles', 'application_submitted_at')
    # ### end Alembic commands ###
