"""add_reviewed_by_kind

Phase 8b — delegated review audit trail. Adds a single nullable column
to member_challenge_completions so the system can record WHO actually
reviewed each submission:

  * "admin"               — SwimBuddz HQ approval
  * "pod_lead"            — Pod Lead of the submitter's active pod
  * "assistant_pod_lead"  — Assistant Pod Lead of that pod

Lets the admin oversight UI distinguish HQ approvals from delegated
ones (so HQ can spot-check pod leads who might be rubber-stamping).

Revision ID: 8090db0fea00
Revises: 83d5ad494b80
Create Date: 2026-05-10 20:07:07.621985
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8090db0fea00'
down_revision = '83d5ad494b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_challenge_completions', sa.Column('reviewed_by_kind', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_challenge_completions', 'reviewed_by_kind')
    # ### end Alembic commands ###
