"""fix_agreement_versions_agreement_type_and_clubs_slug_uniqueness_drift

Revision ID: 855e579b1d78
Revises: a4d7086677ea
Create Date: 2026-05-10 14:05:49.082186
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855e579b1d78'
down_revision = 'a4d7086677ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement_versions', sa.Column('agreement_type', sa.String(length=40), server_default='coach_agreement', nullable=False))
    op.create_index('uq_agreement_current_per_type', 'agreement_versions', ['agreement_type'], unique=True, postgresql_where='is_current = true')
    op.create_unique_constraint('uq_agreement_version_per_type', 'agreement_versions', ['agreement_type', 'version'])
    op.drop_index(op.f('ix_clubs_slug'), table_name='clubs')
    op.create_index(op.f('ix_clubs_slug'), 'clubs', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clubs_slug'), table_name='clubs')
    op.create_index(op.f('ix_clubs_slug'), 'clubs', ['slug'], unique=False)
    op.drop_constraint('uq_agreement_version_per_type', 'agreement_versions', type_='unique')
    op.drop_index('uq_agreement_current_per_type', table_name='agreement_versions', postgresql_where='is_current = true')
    op.drop_column('agreement_versions', 'agreement_type')
    # ### end Alembic commands ###
