"""add_club_notes_and_billing_fields

Revision ID: a6ac42c5717f
Revises: b2d0f6b1ed51
Create Date: 2025-12-17 14:21:15.787024
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ac42c5717f'
down_revision = 'b2d0f6b1ed51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('club_notes', sa.String(), nullable=True))
    op.add_column('members', sa.Column('academy_paid_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('members', sa.Column('academy_alumni', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('members', sa.Column('community_paid_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('members', sa.Column('club_paid_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'club_paid_until')
    op.drop_column('members', 'community_paid_until')
    op.drop_column('members', 'academy_alumni')
    op.drop_column('members', 'academy_paid_until')
    op.drop_column('members', 'club_notes')
    # ### end Alembic commands ###
