"""initial_migration

Revision ID: da791053cab8
Revises: 
Create Date: 2025-11-30 23:32:22.482481
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da791053cab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('challenge_type', sa.String(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('criteria_json', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_challenge_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_data', sa.String(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registration_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('swim_level', sa.String(), nullable=True),
    sa.Column('deep_water_comfort', sa.String(), nullable=True),
    sa.Column('strokes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('goals_narrative', sa.String(), nullable=True),
    sa.Column('goals_other', sa.String(), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('coaching_experience', sa.String(), nullable=True),
    sa.Column('coaching_specialties', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('coaching_years', sa.String(), nullable=True),
    sa.Column('coaching_portfolio_link', sa.String(), nullable=True),
    sa.Column('coaching_document_link', sa.String(), nullable=True),
    sa.Column('coaching_document_file_name', sa.String(), nullable=True),
    sa.Column('availability_slots', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('time_of_day_availability', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('location_preference', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('location_preference_other', sa.String(), nullable=True),
    sa.Column('travel_flexibility', sa.String(), nullable=True),
    sa.Column('facility_access', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('facility_access_other', sa.String(), nullable=True),
    sa.Column('equipment_needs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('equipment_needs_other', sa.String(), nullable=True),
    sa.Column('travel_notes', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('emergency_contact_region', sa.String(), nullable=True),
    sa.Column('medical_info', sa.String(), nullable=True),
    sa.Column('safety_notes', sa.String(), nullable=True),
    sa.Column('volunteer_interest', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('volunteer_roles_detail', sa.String(), nullable=True),
    sa.Column('discovery_source', sa.String(), nullable=True),
    sa.Column('social_instagram', sa.String(), nullable=True),
    sa.Column('social_linkedin', sa.String(), nullable=True),
    sa.Column('social_other', sa.String(), nullable=True),
    sa.Column('language_preference', sa.String(), nullable=True),
    sa.Column('comms_preference', sa.String(), nullable=True),
    sa.Column('payment_readiness', sa.String(), nullable=True),
    sa.Column('currency_preference', sa.String(), nullable=True),
    sa.Column('consent_photo', sa.String(), nullable=True),
    sa.Column('membership_tiers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('academy_focus_areas', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('academy_focus', sa.String(), nullable=True),
    sa.Column('payment_notes', sa.String(), nullable=True),
    sa.Column('membership_tier', sa.String(), server_default='community', nullable=False),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_in_directory', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('interest_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('club_badges_earned', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('club_challenges_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('punctuality_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('commitment_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('academy_skill_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('academy_goals', sa.String(), nullable=True),
    sa.Column('academy_preferred_coach_gender', sa.String(), nullable=True),
    sa.Column('academy_lesson_preference', sa.String(), nullable=True),
    sa.Column('academy_certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('academy_graduation_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_auth_id'), 'members', ['auth_id'], unique=True)
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_table('pending_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_data_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_registrations_email'), 'pending_registrations', ['email'], unique=True)
    op.create_table('volunteer_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slots_available', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_roles')
    op.drop_table('volunteer_interests')
    op.drop_index(op.f('ix_pending_registrations_email'), table_name='pending_registrations')
    op.drop_table('pending_registrations')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_index(op.f('ix_members_auth_id'), table_name='members')
    op.drop_table('members')
    op.drop_table('member_challenge_completions')
    op.drop_table('club_challenges')
    # ### end Alembic commands ###
