"""add_submission_revoke_fields

HQ-override revocation columns (admin audit follow-up to Phase 8b).

Adds three nullable columns to member_challenge_completions:
  * revoked_at  — when HQ revoked the previously-approved submission
  * revoked_by  — admin auth UUID who revoked it
  * revoke_note — required reason, surfaced to the member in-app

Plus one nullable column to challenge_badge_awards:
  * revoked_at  — set when the underlying approval is revoked, so the
    badge stops showing on the profile / public surfaces. Row stays in
    the table for audit; queries filter `revoked_at IS NULL`.

Original review fields (reviewed_by, reviewed_by_kind, reviewed_at,
review_note) are intentionally untouched on revoke — the audit trail
needs to keep "who originally approved" alongside "who revoked it."

Revision ID: ea1abb0ac590
Revises: 8090db0fea00
Create Date: 2026-05-10 20:42:07.319540
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1abb0ac590'
down_revision = '8090db0fea00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_badge_awards', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('revoked_by', sa.UUID(), nullable=True))
    op.add_column('member_challenge_completions', sa.Column('revoke_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_challenge_completions', 'revoke_note')
    op.drop_column('member_challenge_completions', 'revoked_by')
    op.drop_column('member_challenge_completions', 'revoked_at')
    op.drop_column('challenge_badge_awards', 'revoked_at')
    # ### end Alembic commands ###
