"""initial_migration

Revision ID: f96a20b44030
Revises: 
Create Date: 2026-02-01 08:41:32.056339
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f96a20b44030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('challenge_type', sa.String(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('criteria_json', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_challenge_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_data', sa.String(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registration_complete', sa.Boolean(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), server_default='{member}', nullable=False),
    sa.Column('approval_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('approval_notes', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('profile_photo_media_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_auth_id'), 'members', ['auth_id'], unique=True)
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_table('pending_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_data_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_registrations_email'), 'pending_registrations', ['email'], unique=True)
    op.create_table('volunteer_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slots_available', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('paystack_recipient_code', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('coach_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('coach_profile_photo_media_id', sa.UUID(), nullable=True),
    sa.Column('short_bio', sa.String(), nullable=True),
    sa.Column('full_bio', sa.Text(), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('other_certifications_note', sa.Text(), nullable=True),
    sa.Column('coaching_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('coaching_experience_summary', sa.Text(), nullable=True),
    sa.Column('coaching_specialties', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('levels_taught', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('age_groups_taught', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_cohort_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('languages_spoken', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('coaching_portfolio_link', sa.String(), nullable=True),
    sa.Column('coaching_document_link', sa.String(), nullable=True),
    sa.Column('coaching_document_file_name', sa.String(), nullable=True),
    sa.Column('has_cpr_training', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cpr_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifeguard_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('background_check_status', sa.String(), server_default='not_required', nullable=False),
    sa.Column('background_check_document_media_id', sa.UUID(), nullable=True),
    sa.Column('insurance_status', sa.String(), server_default='none', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pools_supported', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('can_travel_between_pools', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('travel_radius_km', sa.Float(), nullable=True),
    sa.Column('max_swimmers_per_session', sa.Integer(), server_default='10', nullable=False),
    sa.Column('max_cohorts_at_once', sa.Integer(), server_default='1', nullable=False),
    sa.Column('accepts_one_on_one', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('accepts_group_cohorts', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('availability_calendar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currency', sa.String(), server_default='NGN', nullable=False),
    sa.Column('one_to_one_rate_per_hour', sa.Integer(), nullable=True),
    sa.Column('group_session_rate_per_hour', sa.Integer(), nullable=True),
    sa.Column('academy_cohort_stipend', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('application_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_reviewed_by', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('show_in_directory', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('average_rating', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('member_availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('available_days', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_times', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('accessible_facilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('travel_flexibility', sa.String(), nullable=True),
    sa.Column('equipment_needed', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('member_emergency_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact_relationship', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('medical_info', sa.String(), nullable=True),
    sa.Column('safety_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('member_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('primary_tier', sa.String(), server_default='community', nullable=False),
    sa.Column('active_tiers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('requested_tiers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('community_paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('club_paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('academy_paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_payment_reference', sa.String(length=50), nullable=True),
    sa.Column('club_badges_earned', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('club_challenges_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('punctuality_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('commitment_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('club_notes', sa.String(), nullable=True),
    sa.Column('academy_skill_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('academy_goals', sa.String(), nullable=True),
    sa.Column('academy_preferred_coach_gender', sa.String(), nullable=True),
    sa.Column('academy_lesson_preference', sa.String(), nullable=True),
    sa.Column('academy_certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('academy_graduation_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('academy_alumni', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('academy_focus_areas', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index(op.f('ix_member_memberships_pending_payment_reference'), 'member_memberships', ['pending_payment_reference'], unique=False)
    op.create_table('member_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('language_preference', sa.String(), nullable=True),
    sa.Column('comms_preference', sa.String(), nullable=True),
    sa.Column('payment_readiness', sa.String(), nullable=True),
    sa.Column('currency_preference', sa.String(), nullable=True),
    sa.Column('consent_photo', sa.String(), nullable=True),
    sa.Column('community_rules_accepted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('volunteer_interest', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('volunteer_roles_detail', sa.String(), nullable=True),
    sa.Column('discovery_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('member_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('area_in_lagos', sa.String(), nullable=True),
    sa.Column('swim_level', sa.String(), nullable=True),
    sa.Column('deep_water_comfort', sa.String(), nullable=True),
    sa.Column('strokes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('personal_goals', sa.String(), nullable=True),
    sa.Column('how_found_us', sa.String(), nullable=True),
    sa.Column('previous_communities', sa.String(), nullable=True),
    sa.Column('hopes_from_swimbuddz', sa.String(), nullable=True),
    sa.Column('social_instagram', sa.String(), nullable=True),
    sa.Column('social_linkedin', sa.String(), nullable=True),
    sa.Column('social_other', sa.String(), nullable=True),
    sa.Column('show_in_directory', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('interest_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_profiles')
    op.drop_table('member_preferences')
    op.drop_index(op.f('ix_member_memberships_pending_payment_reference'), table_name='member_memberships')
    op.drop_table('member_memberships')
    op.drop_table('member_emergency_contacts')
    op.drop_table('member_availabilities')
    op.drop_table('coach_profiles')
    op.drop_table('coach_bank_accounts')
    op.drop_table('volunteer_roles')
    op.drop_table('volunteer_interests')
    op.drop_index(op.f('ix_pending_registrations_email'), table_name='pending_registrations')
    op.drop_table('pending_registrations')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_index(op.f('ix_members_auth_id'), table_name='members')
    op.drop_table('members')
    op.drop_table('member_challenge_completions')
    op.drop_table('club_challenges')
    # ### end Alembic commands ###
