"""initial_migration

Revision ID: 92cbc8a49e72
Revises:
Create Date: 2025-12-02 04:18:09.579583
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92cbc8a49e72"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ride_areas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "pickup_locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("area_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["ride_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_ride_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("ride_area_id", sa.UUID(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ride_area_id"], ["ride_areas.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_ride_configs_session_id"),
        "session_ride_configs",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "ride_bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("session_ride_config_id", sa.UUID(), nullable=False),
        sa.Column("pickup_location_id", sa.UUID(), nullable=False),
        sa.Column("assigned_ride_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pickup_location_id"],
            ["pickup_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_ride_config_id"], ["session_ride_configs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "member_id", name="uq_session_member_booking"
        ),
    )
    op.create_index(
        op.f("ix_ride_bookings_member_id"), "ride_bookings", ["member_id"], unique=False
    )
    op.create_index(
        op.f("ix_ride_bookings_session_id"),
        "ride_bookings",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "route_info",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("origin_area_id", sa.UUID(), nullable=True),
        sa.Column("origin_pickup_location_id", sa.UUID(), nullable=True),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column("destination_name", sa.String(), nullable=False),
        sa.Column("distance_text", sa.String(), nullable=False),
        sa.Column("duration_text", sa.String(), nullable=False),
        sa.Column("departure_offset_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_area_id"],
            ["ride_areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_pickup_location_id"],
            ["pickup_locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("route_info")
    op.drop_index(op.f("ix_ride_bookings_session_id"), table_name="ride_bookings")
    op.drop_index(op.f("ix_ride_bookings_member_id"), table_name="ride_bookings")
    op.drop_table("ride_bookings")
    op.drop_index(
        op.f("ix_session_ride_configs_session_id"), table_name="session_ride_configs"
    )
    op.drop_table("session_ride_configs")
    op.drop_table("pickup_locations")
    op.drop_table("ride_areas")
    # ### end Alembic commands ###
