"""add outreach pause and started_at to corporate_contacts

Revision ID: 020e42066bf4
Revises: 4664032242a0
Create Date: 2026-05-22 13:04:14.487750
"""

revision = "020e42066bf4"
down_revision = '4664032242a0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_contacts', sa.Column('outreach_paused', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('corporate_contacts', sa.Column('outreach_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_contacts', 'outreach_started_at')
    op.drop_column('corporate_contacts', 'outreach_paused')
    # ### end Alembic commands ###
