"""initial corporate service schema

Revision ID: 4664032242a0
Revises:
Create Date: 2026-05-22
"""

revision = "4664032242a0"
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.Enum('tech', 'bank_finance', 'consultancy', 'telco', 'mda_parastatal', 'fmcg', 'healthcare', 'education', 'ngo', 'other', name='corporate_company_industry_enum'), nullable=True),
    sa.Column('company_size', sa.Enum('under_50', '50_to_250', '250_to_1000', 'over_1000', name='corporate_company_size_enum'), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=False),
    sa.Column('primary_contact_role', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=False),
    sa.Column('primary_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('primary_contact_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Enum('cold_outbound', 'warm_intro', 'referral', 'inbound_email', 'inbound_web', 'event', 'other', name='corporate_contact_source_enum'), server_default='cold_outbound', nullable=False),
    sa.Column('owner_auth_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_contacts_company_name'), 'corporate_contacts', ['company_name'], unique=False)
    op.create_index(op.f('ix_corporate_contacts_owner_auth_id'), 'corporate_contacts', ['owner_auth_id'], unique=False)
    op.create_index(op.f('ix_corporate_contacts_primary_contact_email'), 'corporate_contacts', ['primary_contact_email'], unique=False)
    op.create_table('corporate_deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.Enum('lead', 'contacted', 'intro_scheduled', 'intro_done', 'proposal_sent', 'negotiating', 'won', 'lost', name='corporate_deal_stage_enum'), server_default='lead', nullable=False),
    sa.Column('expected_employees', sa.Integer(), nullable=True),
    sa.Column('expected_discount_tier', sa.Enum('full_price', 'bulk_5_9', 'bulk_10_plus', name='corporate_discount_tier_enum'), nullable=True),
    sa.Column('expected_total_kobo', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('actual_close_date', sa.Date(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_due', sa.Date(), nullable=True),
    sa.Column('last_touch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.Enum('price', 'timing', 'internal_priorities', 'budget_frozen', 'competitor', 'logistics', 'no_response', 'other', name='corporate_deal_lost_reason_enum'), nullable=True),
    sa.Column('lost_notes', sa.Text(), nullable=True),
    sa.Column('owner_auth_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['corporate_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_deals_contact_id'), 'corporate_deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_corporate_deals_owner_auth_id'), 'corporate_deals', ['owner_auth_id'], unique=False)
    op.create_index(op.f('ix_corporate_deals_stage'), 'corporate_deals', ['stage'], unique=False)
    op.create_table('corporate_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'active', 'completed', 'cancelled', name='corporate_program_status_enum'), server_default='draft', nullable=False),
    sa.Column('employee_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_tier', sa.Enum('full_price', 'bulk_5_9', 'bulk_10_plus', name='corporate_program_discount_tier_enum'), server_default='full_price', nullable=False),
    sa.Column('per_employee_kobo', sa.Integer(), nullable=False),
    sa.Column('total_kobo', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.Enum('full_upfront', 'deposit_half', 'net_30', 'net_60', 'custom', name='corporate_program_payment_terms_enum'), server_default='deposit_half', nullable=False),
    sa.Column('deposit_paid_kobo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('balance_paid_kobo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('corporate_wallet_id', sa.UUID(), nullable=True),
    sa.Column('expected_start_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('is_pilot_partner', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['corporate_contacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['corporate_deals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_programs_cohort_id'), 'corporate_programs', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_corporate_programs_contact_id'), 'corporate_programs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_corporate_programs_corporate_wallet_id'), 'corporate_programs', ['corporate_wallet_id'], unique=False)
    op.create_index(op.f('ix_corporate_programs_deal_id'), 'corporate_programs', ['deal_id'], unique=True)
    op.create_index(op.f('ix_corporate_programs_status'), 'corporate_programs', ['status'], unique=False)
    op.create_table('corporate_touchpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('email_intro', 'email_followup_1', 'email_followup_2', 'intro_call', 'proposal_shared', 'demo', 'whatsapp', 'phone_call', 'in_person', 'note', name='corporate_touchpoint_type_enum'), nullable=False),
    sa.Column('direction', sa.Enum('outbound', 'inbound', name='corporate_touchpoint_direction_enum'), server_default='outbound', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('logged_by_auth_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['corporate_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['corporate_deals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_touchpoints_contact_id'), 'corporate_touchpoints', ['contact_id'], unique=False)
    op.create_index(op.f('ix_corporate_touchpoints_deal_id'), 'corporate_touchpoints', ['deal_id'], unique=False)
    op.create_index(op.f('ix_corporate_touchpoints_occurred_at'), 'corporate_touchpoints', ['occurred_at'], unique=False)
    op.create_table('corporate_program_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('member_auth_id', sa.String(length=255), nullable=True),
    sa.Column('enrollment_status', sa.Enum('pending', 'invited', 'registered', 'enrolled', 'opted_out', name='corporate_employee_enrollment_status_enum'), server_default='pending', nullable=False),
    sa.Column('invitation_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['corporate_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'email', name='uq_corporate_program_employee_email')
    )
    op.create_index(op.f('ix_corporate_program_employees_email'), 'corporate_program_employees', ['email'], unique=False)
    op.create_index(op.f('ix_corporate_program_employees_enrollment_status'), 'corporate_program_employees', ['enrollment_status'], unique=False)
    op.create_index(op.f('ix_corporate_program_employees_member_auth_id'), 'corporate_program_employees', ['member_auth_id'], unique=False)
    op.create_index(op.f('ix_corporate_program_employees_member_id'), 'corporate_program_employees', ['member_id'], unique=False)
    op.create_index(op.f('ix_corporate_program_employees_program_id'), 'corporate_program_employees', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_program_employees_program_id'), table_name='corporate_program_employees')
    op.drop_index(op.f('ix_corporate_program_employees_member_id'), table_name='corporate_program_employees')
    op.drop_index(op.f('ix_corporate_program_employees_member_auth_id'), table_name='corporate_program_employees')
    op.drop_index(op.f('ix_corporate_program_employees_enrollment_status'), table_name='corporate_program_employees')
    op.drop_index(op.f('ix_corporate_program_employees_email'), table_name='corporate_program_employees')
    op.drop_table('corporate_program_employees')
    op.drop_index(op.f('ix_corporate_touchpoints_occurred_at'), table_name='corporate_touchpoints')
    op.drop_index(op.f('ix_corporate_touchpoints_deal_id'), table_name='corporate_touchpoints')
    op.drop_index(op.f('ix_corporate_touchpoints_contact_id'), table_name='corporate_touchpoints')
    op.drop_table('corporate_touchpoints')
    op.drop_index(op.f('ix_corporate_programs_status'), table_name='corporate_programs')
    op.drop_index(op.f('ix_corporate_programs_deal_id'), table_name='corporate_programs')
    op.drop_index(op.f('ix_corporate_programs_corporate_wallet_id'), table_name='corporate_programs')
    op.drop_index(op.f('ix_corporate_programs_contact_id'), table_name='corporate_programs')
    op.drop_index(op.f('ix_corporate_programs_cohort_id'), table_name='corporate_programs')
    op.drop_table('corporate_programs')
    op.drop_index(op.f('ix_corporate_deals_stage'), table_name='corporate_deals')
    op.drop_index(op.f('ix_corporate_deals_owner_auth_id'), table_name='corporate_deals')
    op.drop_index(op.f('ix_corporate_deals_contact_id'), table_name='corporate_deals')
    op.drop_table('corporate_deals')
    op.drop_index(op.f('ix_corporate_contacts_primary_contact_email'), table_name='corporate_contacts')
    op.drop_index(op.f('ix_corporate_contacts_owner_auth_id'), table_name='corporate_contacts')
    op.drop_index(op.f('ix_corporate_contacts_company_name'), table_name='corporate_contacts')
    op.drop_table('corporate_contacts')
    # ### end Alembic commands ###
