"""add_auth_id_to_member_ref_convert_cost_to_kobo

Revision ID: 0906d2bdb5d9
Revises: 50acb9c251f5
Create Date: 2026-02-24 16:22:05.195677
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0906d2bdb5d9'
down_revision = '50acb9c251f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Converts existing naira float values → kobo integers (×100) for prod safety.
    op.alter_column('session_ride_configs', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="ROUND(cost * 100)::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_ride_configs', 'cost',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               postgresql_using="(cost / 100.0)::double precision")
    # ### end Alembic commands ###
