"""add_num_seats_to_ride_bookings

Revision ID: 9eea2f4b0588
Revises: 0906d2bdb5d9
Create Date: 2026-03-12 14:31:56.142862
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eea2f4b0588'
down_revision = '0906d2bdb5d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_bookings', sa.Column('num_seats', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_bookings', 'num_seats')
    # ### end Alembic commands ###
