"""initial_migration

Revision ID: b2768f463301
Revises: 
Create Date: 2025-11-28 21:29:11.523534
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2768f463301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ride_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('ride_share_option', sa.Enum('NONE', 'LEAD', 'JOIN', name='ride_share_option_enum'), nullable=False),
    sa.Column('needs_ride', sa.Boolean(), nullable=False),
    sa.Column('can_offer_ride', sa.Boolean(), nullable=False),
    sa.Column('ride_notes', sa.String(), nullable=True),
    sa.Column('pickup_location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_preferences_member_id'), 'ride_preferences', ['member_id'], unique=False)
    op.create_index(op.f('ix_ride_preferences_session_id'), 'ride_preferences', ['session_id'], unique=False)
    op.create_table('pickup_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['ride_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin_area_id', sa.UUID(), nullable=True),
    sa.Column('origin_pickup_location_id', sa.UUID(), nullable=True),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('destination_name', sa.String(), nullable=False),
    sa.Column('distance_text', sa.String(), nullable=False),
    sa.Column('duration_text', sa.String(), nullable=False),
    sa.Column('departure_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_area_id'], ['ride_areas.id'], ),
    sa.ForeignKeyConstraint(['origin_pickup_location_id'], ['pickup_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_info')
    op.drop_table('pickup_locations')
    op.drop_index(op.f('ix_ride_preferences_session_id'), table_name='ride_preferences')
    op.drop_index(op.f('ix_ride_preferences_member_id'), table_name='ride_preferences')
    op.drop_table('ride_preferences')
    op.drop_table('ride_areas')
    # ### end Alembic commands ###
