"""add_destination_pool_id_to_route_info

Revision ID: be5f99aaf6bc
Revises: 9eea2f4b0588
Create Date: 2026-04-19 06:57:53.113649
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5f99aaf6bc'
down_revision = '9eea2f4b0588'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_info', sa.Column('destination_pool_id', sa.UUID(), nullable=True))
    op.alter_column('route_info', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_route_info_destination_pool_id'), 'route_info', ['destination_pool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_info_destination_pool_id'), table_name='route_info')
    op.alter_column('route_info', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('route_info', 'destination_pool_id')
    # ### end Alembic commands ###
