"""Communications Service schemas package."""

from services.communications_service.schemas.main import (
    AnnouncementBase,
    AnnouncementCategoryConfigCreate,
    AnnouncementCategoryConfigResponse,
    AnnouncementCategoryConfigUpdate,
    AnnouncementCommentResponse,
    AnnouncementCreate,
    AnnouncementReadCreate,
    AnnouncementReadResponse,
    AnnouncementResponse,
    AnnouncementUpdate,
    CohortMessageCreate,
    CommentCreate,
    ContentCommentResponse,
    ContentPostBase,
    ContentPostCreate,
    ContentPostResponse,
    ContentPostUpdate,
    MessageCreate,
    MessageLogResponse,
    MessageResponse,
    NotificationPreferencesBase,
    NotificationPreferencesResponse,
    NotificationPreferencesUpdate,
    StudentMessageCreate,
)

__all__ = [
    "AnnouncementBase",
    "AnnouncementCategoryConfigCreate",
    "AnnouncementCategoryConfigResponse",
    "AnnouncementCategoryConfigUpdate",
    "AnnouncementCommentResponse",
    "AnnouncementCreate",
    "AnnouncementReadCreate",
    "AnnouncementReadResponse",
    "AnnouncementResponse",
    "AnnouncementUpdate",
    "CohortMessageCreate",
    "CommentCreate",
    "ContentCommentResponse",
    "ContentPostBase",
    "ContentPostCreate",
    "ContentPostResponse",
    "ContentPostUpdate",
    "MessageCreate",
    "MessageLogResponse",
    "MessageResponse",
    "NotificationPreferencesBase",
    "NotificationPreferencesResponse",
    "NotificationPreferencesUpdate",
    "StudentMessageCreate",
]
