"""expand_payments_model

Revision ID: 0a72aa81d384
Revises: 74eaefb0f6ea
Create Date: 2025-12-17 14:27:39.819876
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a72aa81d384'
down_revision = '74eaefb0f6ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_purpose_enum = postgresql.ENUM(
        'COMMUNITY_ANNUAL',
        'COMMUNITY_EVENT',
        'CLUB_MONTHLY',
        'CLUB_QUATERLY',
        'CLUB_BIANNUALLY',
        'CLUB_ANNUALLY',
        'ACADEMY_COHORT',
        'POOL_FEE',
        'RIDE_SHARE',
        name='payment_purpose_enum',
    )
    payment_purpose_enum.create(op.get_bind(), checkfirst=True)

    # Existing rows (if any) predate these columns; add safe defaults then remove defaults.
    op.add_column('payments', sa.Column('member_auth_id', sa.String(), server_default='', nullable=False))
    op.add_column('payments', sa.Column('payer_email', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('purpose', payment_purpose_enum, server_default='COMMUNITY_ANNUAL', nullable=False))
    op.add_column('payments', sa.Column('currency', sa.String(length=8), server_default='NGN', nullable=False))
    op.add_column('payments', sa.Column('provider', sa.String(length=32), nullable=True))
    op.add_column('payments', sa.Column('provider_reference', sa.String(length=128), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('entitlement_applied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('entitlement_error', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_payments_member_auth_id'), 'payments', ['member_auth_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_email'), 'payments', ['payer_email'], unique=False)
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=False)

    op.alter_column('payments', 'member_auth_id', server_default=None)
    op.alter_column('payments', 'purpose', server_default=None)
    op.alter_column('payments', 'currency', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_email'), table_name='payments')
    op.drop_index(op.f('ix_payments_member_auth_id'), table_name='payments')
    op.drop_column('payments', 'metadata')
    op.drop_column('payments', 'entitlement_error')
    op.drop_column('payments', 'entitlement_applied_at')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'provider_reference')
    op.drop_column('payments', 'provider')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'purpose')
    op.drop_column('payments', 'payer_email')
    op.drop_column('payments', 'member_auth_id')

    payment_purpose_enum = postgresql.ENUM(name='payment_purpose_enum')
    payment_purpose_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
