"""add_config_id_and_block_index_to_coach_payouts

Revision ID: 36dbbd8ca925
Revises: a6a13b72dd6d
Create Date: 2026-06-24 06:11:49.554431
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dbbd8ca925'
down_revision = 'a6a13b72dd6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_payouts', sa.Column('config_id', sa.UUID(), nullable=True))
    op.add_column('coach_payouts', sa.Column('block_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_coach_payouts_config_id'), 'coach_payouts', ['config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_payouts_config_id'), table_name='coach_payouts')
    op.drop_column('coach_payouts', 'block_index')
    op.drop_column('coach_payouts', 'config_id')
    # ### end Alembic commands ###
