"""initial_migration

Revision ID: 4966c6aeeb0e
Revises: 
Create Date: 2025-12-29 10:53:49.619181
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4966c6aeeb0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('member_auth_id', sa.String(), nullable=False),
    sa.Column('payer_email', sa.String(), nullable=True),
    sa.Column('purpose', sa.Enum('COMMUNITY_ANNUAL', 'COMMUNITY_EVENT', 'CLUB_MONTHLY', 'CLUB_QUATERLY', 'CLUB_BIANNUALLY', 'CLUB_ANNUALLY', 'CLUB_ACTIVATION', 'ACADEMY_COHORT', 'POOL_FEE', 'RIDE_SHARE', name='payment_purpose_enum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'WAIVED', 'FAILED', name='payment_status_enum'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entitlement_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entitlement_error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_member_auth_id'), 'payments', ['member_auth_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_email'), 'payments', ['payer_email'], unique=False)
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_email'), table_name='payments')
    op.drop_index(op.f('ix_payments_member_auth_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
