"""add_paystack_settlements_table

Revision ID: 7002342f75af
Revises: 3620e052a0b6
Create Date: 2026-06-02 10:04:37.663157
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7002342f75af"
down_revision = "3620e052a0b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paystack_settlements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paystack_settlement_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("gross_minor", sa.BigInteger(), nullable=False),
        sa.Column("fees_minor", sa.BigInteger(), nullable=False),
        sa.Column("net_minor", sa.BigInteger(), nullable=False),
        sa.Column("settlement_date", sa.Date(), nullable=True),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("ledger_posted", sa.Boolean(), nullable=False),
        sa.Column("ledger_posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paystack_settlements_ledger_posted"),
        "paystack_settlements",
        ["ledger_posted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paystack_settlements_paystack_settlement_id"),
        "paystack_settlements",
        ["paystack_settlement_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_paystack_settlements_settlement_date"),
        "paystack_settlements",
        ["settlement_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paystack_settlements_status"),
        "paystack_settlements",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_paystack_settlements_status"), table_name="paystack_settlements"
    )
    op.drop_index(
        op.f("ix_paystack_settlements_settlement_date"),
        table_name="paystack_settlements",
    )
    op.drop_index(
        op.f("ix_paystack_settlements_paystack_settlement_id"),
        table_name="paystack_settlements",
    )
    op.drop_index(
        op.f("ix_paystack_settlements_ledger_posted"), table_name="paystack_settlements"
    )
    op.drop_table("paystack_settlements")
    # ### end Alembic commands ###
