"""initial_migration

Revision ID: 74eaefb0f6ea
Revises: 
Create Date: 2025-12-02 04:15:52.691171
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74eaefb0f6ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'WAIVED', 'FAILED', name='payment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
