"""add_recurring_payouts_and_makeups

Revision ID: 8bad74e751fb
Revises: b4c8d2e5f3a1
Create Date: 2026-05-02 01:04:44.777993
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bad74e751fb'
down_revision = 'b4c8d2e5f3a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_makeup_obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('student_member_id', sa.UUID(), nullable=False),
    sa.Column('coach_member_id', sa.UUID(), nullable=False),
    sa.Column('original_session_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_session_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('late_join', 'excused_absence', 'session_cancelled', name='makeup_reason_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'scheduled', 'completed', 'expired', 'cancelled', name='makeup_status_enum'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pay_credited_in_payout_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_makeup_obligations_coach_member_id'), 'cohort_makeup_obligations', ['coach_member_id'], unique=False)
    op.create_index(op.f('ix_cohort_makeup_obligations_cohort_id'), 'cohort_makeup_obligations', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_makeup_obligations_scheduled_session_id'), 'cohort_makeup_obligations', ['scheduled_session_id'], unique=False)
    op.create_index(op.f('ix_cohort_makeup_obligations_status'), 'cohort_makeup_obligations', ['status'], unique=False)
    op.create_index(op.f('ix_cohort_makeup_obligations_student_member_id'), 'cohort_makeup_obligations', ['student_member_id'], unique=False)
    # Partial unique dedupe index: prevents duplicate make-up obligations for
    # the same (cohort, student, original_session, reason) combination.
    # Manual addition — Alembic autogen does not generate partial indexes.
    op.create_index(
        'ix_cohort_makeup_obligations_dedupe',
        'cohort_makeup_obligations',
        ['cohort_id', 'student_member_id', 'original_session_id', 'reason'],
        unique=True,
        postgresql_where=sa.text('original_session_id IS NOT NULL'),
    )
    op.create_table('recurring_payout_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_member_id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('band_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_blocks', sa.Integer(), nullable=False),
    sa.Column('block_length_days', sa.Integer(), nullable=False),
    sa.Column('cohort_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cohort_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cohort_price_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('next_run_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'cancelled', name='recurring_payout_status_enum'), nullable=False),
    sa.Column('created_by_member_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_member_id', 'cohort_id', name='uq_recurring_payout_coach_cohort')
    )
    op.create_index(op.f('ix_recurring_payout_configs_coach_member_id'), 'recurring_payout_configs', ['coach_member_id'], unique=False)
    op.create_index(op.f('ix_recurring_payout_configs_cohort_id'), 'recurring_payout_configs', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_recurring_payout_configs_next_run_date'), 'recurring_payout_configs', ['next_run_date'], unique=False)
    op.create_index(op.f('ix_recurring_payout_configs_status'), 'recurring_payout_configs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_payout_configs_status'), table_name='recurring_payout_configs')
    op.drop_index(op.f('ix_recurring_payout_configs_next_run_date'), table_name='recurring_payout_configs')
    op.drop_index(op.f('ix_recurring_payout_configs_cohort_id'), table_name='recurring_payout_configs')
    op.drop_index(op.f('ix_recurring_payout_configs_coach_member_id'), table_name='recurring_payout_configs')
    op.drop_table('recurring_payout_configs')
    op.drop_index(op.f('ix_cohort_makeup_obligations_student_member_id'), table_name='cohort_makeup_obligations')
    op.drop_index('ix_cohort_makeup_obligations_dedupe', table_name='cohort_makeup_obligations')
    op.drop_index(op.f('ix_cohort_makeup_obligations_status'), table_name='cohort_makeup_obligations')
    op.drop_index(op.f('ix_cohort_makeup_obligations_scheduled_session_id'), table_name='cohort_makeup_obligations')
    op.drop_index(op.f('ix_cohort_makeup_obligations_cohort_id'), table_name='cohort_makeup_obligations')
    op.drop_index(op.f('ix_cohort_makeup_obligations_coach_member_id'), table_name='cohort_makeup_obligations')
    op.drop_table('cohort_makeup_obligations')
    # ### end Alembic commands ###
