"""initial_migration

Revision ID: e9b95f04e6cf
Revises: 
Create Date: 2026-02-05 04:27:12.706070
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9b95f04e6cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_member_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('academy_earnings', sa.Integer(), nullable=False),
    sa.Column('session_earnings', sa.Integer(), nullable=False),
    sa.Column('other_earnings', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PROCESSING', 'PAID', 'FAILED', name='payout_status_enum'), nullable=False),
    sa.Column('payout_method', sa.Enum('PAYSTACK_TRANSFER', 'BANK_TRANSFER', 'OTHER', name='payout_method_enum'), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('paystack_transfer_code', sa.String(length=50), nullable=True),
    sa.Column('paystack_transfer_status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_payouts_coach_member_id'), 'coach_payouts', ['coach_member_id'], unique=False)
    op.create_table('discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discount_type_enum'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('applies_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discounts_code'), 'discounts', ['code'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('member_auth_id', sa.String(), nullable=False),
    sa.Column('payer_email', sa.String(), nullable=True),
    sa.Column('purpose', sa.Enum('COMMUNITY', 'CLUB', 'CLUB_BUNDLE', 'ACADEMY_COHORT', 'SESSION_FEE', 'STORE_ORDER', name='payment_purpose_enum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PENDING_REVIEW', 'PAID', 'WAIVED', 'FAILED', name='payment_status_enum'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('proof_of_payment_media_id', sa.UUID(), nullable=True),
    sa.Column('admin_review_note', sa.Text(), nullable=True),
    sa.Column('entitlement_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entitlement_error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_member_auth_id'), 'payments', ['member_auth_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_email'), 'payments', ['payer_email'], unique=False)
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_email'), table_name='payments')
    op.drop_index(op.f('ix_payments_member_auth_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_discounts_code'), table_name='discounts')
    op.drop_table('discounts')
    op.drop_index(op.f('ix_coach_payouts_coach_member_id'), table_name='coach_payouts')
    op.drop_table('coach_payouts')
    # ### end Alembic commands ###
