"""rename_proof_of_payment_url_to_media_id

Revision ID: efe570a06fcc
Revises: 453ddf388978
Create Date: 2026-01-09 17:50:20.924024
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe570a06fcc'
down_revision = '453ddf388978'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('proof_of_payment_media_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'proof_of_payment_media_id')
    # ### end Alembic commands ###
