#!/bin/bash
set -e

# ===============================================================================
# FULL RESET ALL DATABASES
# ===============================================================================
#
# This script performs a full reset on BOTH dev and prod databases.
# It ensures both databases have identical schema and migration files.
#
# Order of operations:
#   1. Full reset DEV (regenerates migrations, seeds data)
#   2. Reset PROD with the same migrations (does NOT regenerate)
#
# This ensures both databases use the same migration file IDs.
#
# Usage:
#   ./scripts/full_reset_all.sh
#
# ===============================================================================

echo "========================================="
echo "SwimBuddz FULL Reset - ALL Databases"
echo "========================================="
echo ""
echo "This will:"
echo "  1. Full reset DEV database (regenerate migrations)"
echo "  2. Reset PROD database (apply same migrations)"
echo ""
echo "Both databases will have identical schema."
echo ""

read -p "Continue? (y/N): " CONFIRM
if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
    echo "Aborted."
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo ""
echo "=================================================================="
echo "PHASE 1: Full Reset DEV Database"
echo "=================================================================="
"$SCRIPT_DIR/full_reset.sh" dev

echo ""
echo "=================================================================="
echo "PHASE 2: Reset PROD Database (using same migrations)"
echo "=================================================================="
echo ""
echo "⚠️  This will reset PRODUCTION!"
read -p "Type 'yes' to confirm PROD reset: " PROD_CONFIRM
if [ "$PROD_CONFIRM" != "yes" ]; then
    echo "PROD reset skipped. DEV was reset successfully."
    exit 0
fi

# For prod, we use reset_db.sh (not full_reset.sh) since migrations
# were already generated by the dev reset
"$SCRIPT_DIR/database/reset_db.sh" prod

echo ""
echo "========================================="
echo "✓ All databases reset successfully!"
echo "========================================="
echo ""
echo "Both DEV and PROD now have identical schema."
echo ""
