"""add_dropped_at_to_enrollments

Revision ID: 0a55b3dcf165
Revises: e4a7f2c31d08
Create Date: 2026-05-02 01:19:02.602246
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a55b3dcf165'
down_revision = 'e4a7f2c31d08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('dropped_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'dropped_at')
    # ### end Alembic commands ###
