"""add_cohort_session_defaults

Revision ID: 1baccbd7cd92
Revises: 5a912f638307
Create Date: 2026-04-19 06:16:55.580550
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1baccbd7cd92'
down_revision = '5a912f638307'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohorts', sa.Column('pool_id', sa.UUID(), nullable=True))
    op.add_column('cohorts', sa.Column('default_pool_fee', sa.Integer(), nullable=True))
    op.add_column('cohorts', sa.Column('default_ride_configs', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_cohorts_pool_id'), 'cohorts', ['pool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohorts_pool_id'), table_name='cohorts')
    op.drop_column('cohorts', 'default_ride_configs')
    op.drop_column('cohorts', 'default_pool_fee')
    op.drop_column('cohorts', 'pool_id')
    # ### end Alembic commands ###
