"""coach_system_updates

Revision ID: 276d1743e1bb
Revises: cb2b7ea743b7
Create Date: 2026-02-06 13:09:11.040775
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "276d1743e1bb"
down_revision = "cb2b7ea743b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coach_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("coach_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_session_override", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("session_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cohort_id"], ["cohorts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coach_assignments_coach_id"),
        "coach_assignments",
        ["coach_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coach_assignments_cohort_id"),
        "coach_assignments",
        ["cohort_id"],
        unique=False,
    )
    op.create_table(
        "shadow_evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("evaluator_id", sa.UUID(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("scores", sa.JSON(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["coach_assignments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shadow_evaluations_assignment_id"),
        "shadow_evaluations",
        ["assignment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shadow_evaluations_assignment_id"), table_name="shadow_evaluations"
    )
    op.drop_table("shadow_evaluations")
    op.drop_index(
        op.f("ix_coach_assignments_cohort_id"), table_name="coach_assignments"
    )
    op.drop_index(op.f("ix_coach_assignments_coach_id"), table_name="coach_assignments")
    op.drop_table("coach_assignments")
    # ### end Alembic commands ###
