"""add_mid_entry_cutoff_week_to_cohorts

Revision ID: 3fa9e0cb8783
Revises: fbde21296114
Create Date: 2026-01-16 07:09:03.134026
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa9e0cb8783'
down_revision = 'fbde21296114'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohorts', sa.Column('mid_entry_cutoff_week', sa.Integer(), server_default='2', nullable=False))
    op.add_column('enrollments', sa.Column('reminders_sent', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('enrollments', sa.Column('certificate_issued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrollments', sa.Column('certificate_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'certificate_code')
    op.drop_column('enrollments', 'certificate_issued_at')
    op.drop_column('enrollments', 'reminders_sent')
    op.drop_column('cohorts', 'mid_entry_cutoff_week')
    # ### end Alembic commands ###
