"""add_enrollment_installments_and_access_flags

Revision ID: 42e8fdc72dce
Revises: 8796297a3336
Create Date: 2026-02-19 06:14:50.765304
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42e8fdc72dce"
down_revision = "8796297a3336"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrollment_installments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("enrollment_id", sa.UUID(), nullable=False),
        sa.Column("installment_number", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PAID", "MISSED", "WAIVED", name="installment_status_enum"
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_reference", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"], ["enrollments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "enrollment_id",
            "installment_number",
            name="uq_enrollment_installment_number",
        ),
    )
    op.create_index(
        op.f("ix_enrollment_installments_enrollment_id"),
        "enrollment_installments",
        ["enrollment_id"],
        unique=False,
    )
    op.add_column(
        "cohorts",
        sa.Column(
            "admin_dropout_approval",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "enrollments",
        sa.Column(
            "total_installments", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "enrollments",
        sa.Column(
            "paid_installments_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "enrollments",
        sa.Column(
            "missed_installments_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "enrollments",
        sa.Column(
            "access_suspended", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # Alembic cannot auto-detect enum value additions — add manually
    op.execute(
        "ALTER TYPE enrollment_status_enum ADD VALUE IF NOT EXISTS 'dropout_pending'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enrollments", "access_suspended")
    op.drop_column("enrollments", "missed_installments_count")
    op.drop_column("enrollments", "paid_installments_count")
    op.drop_column("enrollments", "total_installments")
    op.drop_column("cohorts", "admin_dropout_approval")
    op.drop_index(
        op.f("ix_enrollment_installments_enrollment_id"),
        table_name="enrollment_installments",
    )
    op.drop_table("enrollment_installments")
    sa.Enum("PENDING", "PAID", "MISSED", "WAIVED", name="installment_status_enum").drop(
        op.get_bind(), checkfirst=True
    )
    # PostgreSQL does not support DROP VALUE on an enum directly.
    # Rows with 'dropout_pending' are set back to 'dropped', then the enum
    # is recreated without the value.
    op.execute(
        """
        UPDATE enrollments
        SET status = 'dropped'
        WHERE status = 'dropout_pending'
    """
    )
    op.execute(
        """
        CREATE TYPE enrollment_status_enum_new AS ENUM (
            'pending_approval',
            'enrolled',
            'waitlist',
            'dropped',
            'graduated'
        )
    """
    )
    op.execute(
        """
        ALTER TABLE enrollments
        ALTER COLUMN status TYPE enrollment_status_enum_new
        USING status::text::enrollment_status_enum_new
    """
    )
    op.execute("DROP TYPE enrollment_status_enum")
    op.execute("ALTER TYPE enrollment_status_enum_new RENAME TO enrollment_status_enum")
    # ### end Alembic commands ###
