"""add_evidence_media_id_to_student_progress

Revision ID: 4510740d84ed
Revises: 4840259283f3
Create Date: 2026-01-08 03:37:56.633363
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4510740d84ed'
down_revision = '4840259283f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_progress', sa.Column('evidence_media_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_progress', 'evidence_media_id')
    # ### end Alembic commands ###
