"""add_require_approval_to_cohort

Revision ID: 4840259283f3
Revises: 89d43b843fb9
Create Date: 2026-01-07 03:57:38.706770
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4840259283f3'
down_revision = '89d43b843fb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohorts', sa.Column('require_approval', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cohorts', 'require_approval')
    # ### end Alembic commands ###
