"""add_media_id_fields

Revision ID: 4f2500bba144
Revises: 4510740d84ed
Create Date: 2026-01-08 06:50:04.634848
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2500bba144'
down_revision = '4510740d84ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_lessons', sa.Column('video_media_id', sa.UUID(), nullable=True))
    op.add_column('enrollments', sa.Column('member_auth_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_enrollments_member_auth_id'), 'enrollments', ['member_auth_id'], unique=False)
    op.add_column('milestones', sa.Column('video_media_id', sa.UUID(), nullable=True))
    op.add_column('programs', sa.Column('cover_image_media_id', sa.UUID(), nullable=True))
    op.drop_column('student_progress', 'evidence_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_progress', sa.Column('evidence_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('programs', 'cover_image_media_id')
    op.drop_column('milestones', 'video_media_id')
    op.drop_index(op.f('ix_enrollments_member_auth_id'), table_name='enrollments')
    op.drop_column('enrollments', 'member_auth_id')
    op.drop_column('curriculum_lessons', 'video_media_id')
    # ### end Alembic commands ###
