"""add_cohort_extension_requests

Revision ID: 5a912f638307
Revises: c91f0b98f6b2
Create Date: 2026-03-26 12:32:39.185551
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a912f638307'
down_revision = 'c91f0b98f6b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_extension_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('weeks_requested', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('current_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposed_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='extension_request_status_enum'), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_extension_requests_coach_id'), 'cohort_extension_requests', ['coach_id'], unique=False)
    op.create_index(op.f('ix_cohort_extension_requests_cohort_id'), 'cohort_extension_requests', ['cohort_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_extension_requests_cohort_id'), table_name='cohort_extension_requests')
    op.drop_index(op.f('ix_cohort_extension_requests_coach_id'), table_name='cohort_extension_requests')
    op.drop_table('cohort_extension_requests')
    # ### end Alembic commands ###
