"""add_cohort_resources

Revision ID: 697ee5a199df
Revises: 008672b0c18a
Create Date: 2026-01-27 14:48:36.220302
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697ee5a199df'
down_revision = '008672b0c18a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('URL', 'UPLOAD', name='resource_source_type_enum'), server_default='URL', nullable=False),
    sa.Column('content_media_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'ENROLLED_ONLY', 'COACHES_ONLY', name='resource_visibility_enum'), server_default='ENROLLED_ONLY', nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cohort_resources')
    # ### end Alembic commands ###
