"""add cohort timeline shift logs

Revision ID: 6c350e582705
Revises: a4c5d6e7f801
Create Date: 2026-02-23 17:34:57.012418
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c350e582705'
down_revision = 'a4c5d6e7f801'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_timeline_shift_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('actor_auth_id', sa.String(), nullable=True),
    sa.Column('actor_member_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('old_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delta_seconds', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'idempotency_key', name='uq_cohort_timeline_shift_logs_idempotency')
    )
    op.create_index(op.f('ix_cohort_timeline_shift_logs_cohort_id'), 'cohort_timeline_shift_logs', ['cohort_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_timeline_shift_logs_cohort_id'), table_name='cohort_timeline_shift_logs')
    op.drop_table('cohort_timeline_shift_logs')
    # ### end Alembic commands ###
