"""add_fk_indexes

Revision ID: 7f6b0a2a1c9e
Revises: 0a55b3dcf165
Create Date: 2026-05-16 16:49:21.260635
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6b0a2a1c9e'
down_revision = '0a55b3dcf165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_curriculum_lessons_week_id'), 'curriculum_lessons', ['week_id'], unique=False)
    op.create_index(op.f('ix_curriculum_weeks_curriculum_id'), 'curriculum_weeks', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_enrollments_cohort_id'), 'enrollments', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_enrollments_program_id'), 'enrollments', ['program_id'], unique=False)
    op.create_index(op.f('ix_lesson_skills_lesson_id'), 'lesson_skills', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_skills_skill_id'), 'lesson_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_program_curricula_program_id'), 'program_curricula', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_curricula_program_id'), table_name='program_curricula')
    op.drop_index(op.f('ix_lesson_skills_skill_id'), table_name='lesson_skills')
    op.drop_index(op.f('ix_lesson_skills_lesson_id'), table_name='lesson_skills')
    op.drop_index(op.f('ix_enrollments_program_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_cohort_id'), table_name='enrollments')
    op.drop_index(op.f('ix_curriculum_weeks_curriculum_id'), table_name='curriculum_weeks')
    op.drop_index(op.f('ix_curriculum_lessons_week_id'), table_name='curriculum_lessons')
    # ### end Alembic commands ###
