"""add_cascade_deletes_for_cohort_children

Revision ID: 8796297a3336
Revises: 276d1743e1bb
Create Date: 2026-02-09 22:44:02.546273
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8796297a3336'
down_revision = '276d1743e1bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cohort_complexity_scores_cohort_id_fkey'), 'cohort_complexity_scores', type_='foreignkey')
    op.create_foreign_key(None, 'cohort_complexity_scores', 'cohorts', ['cohort_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cohort_resources_cohort_id_fkey'), 'cohort_resources', type_='foreignkey')
    op.create_foreign_key(None, 'cohort_resources', 'cohorts', ['cohort_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('enrollments_cohort_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'cohorts', ['cohort_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_progress_enrollment_id_fkey'), 'student_progress', type_='foreignkey')
    op.create_foreign_key(None, 'student_progress', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_progress', type_='foreignkey')
    op.create_foreign_key(op.f('student_progress_enrollment_id_fkey'), 'student_progress', 'enrollments', ['enrollment_id'], ['id'])
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_cohort_id_fkey'), 'enrollments', 'cohorts', ['cohort_id'], ['id'])
    op.drop_constraint(None, 'cohort_resources', type_='foreignkey')
    op.create_foreign_key(op.f('cohort_resources_cohort_id_fkey'), 'cohort_resources', 'cohorts', ['cohort_id'], ['id'])
    op.drop_constraint(None, 'cohort_complexity_scores', type_='foreignkey')
    op.create_foreign_key(op.f('cohort_complexity_scores_cohort_id_fkey'), 'cohort_complexity_scores', 'cohorts', ['cohort_id'], ['id'])
    # ### end Alembic commands ###
