"""add_prep_materials_and_resources

Revision ID: 92ab8f61d388
Revises: 7cc71d2490eb
Create Date: 2025-12-11 05:35:41.590232
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ab8f61d388'
down_revision = '7cc71d2490eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohorts', sa.Column('allow_mid_entry', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('enrollments', sa.Column('program_id', sa.UUID(), nullable=True))
    op.add_column('enrollments', sa.Column('preferences', sa.JSON(), nullable=True))
    op.alter_column('enrollments', 'cohort_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'enrollments', 'programs', ['program_id'], ['id'])
    op.add_column('programs', sa.Column('prep_materials', sa.JSON(), nullable=True))
    op.alter_column('programs', 'price',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('programs', 'price',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('programs', 'prep_materials')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.alter_column('enrollments', 'cohort_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('enrollments', 'preferences')
    op.drop_column('enrollments', 'program_id')
    op.drop_column('cohorts', 'allow_mid_entry')
    # ### end Alembic commands ###
