"""add_program_faq_json_field

Revision ID: ba3150f4c374
Revises: 9b6e8f7499d8
Create Date: 2026-05-18 14:13:22.877386
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3150f4c374'
down_revision = '9b6e8f7499d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('faq_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'faq_json')
    # ### end Alembic commands ###
