"""enforce explicit installment opt-in and clean auto-generated schedules

Revision ID: c91f0b98f6b2
Revises: 6c350e582705
Create Date: 2026-02-24 09:40:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c91f0b98f6b2"
down_revision = "6c350e582705"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "enrollments",
        sa.Column(
            "uses_installments",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )

    # Canonical internal money unit: kobo.
    # Existing values in these columns were stored as naira integers.
    op.execute(
        """
        UPDATE programs
        SET price_amount = price_amount * 100
        """
    )
    op.execute(
        """
        UPDATE cohorts
        SET
            price_override = CASE
                WHEN price_override IS NULL THEN NULL
                ELSE price_override * 100
            END,
            installment_deposit_amount = CASE
                WHEN installment_deposit_amount IS NULL THEN NULL
                ELSE installment_deposit_amount * 100
            END
        """
    )
    op.execute(
        """
        UPDATE enrollments
        SET price_snapshot_amount = CASE
            WHEN price_snapshot_amount IS NULL THEN NULL
            ELSE price_snapshot_amount * 100
        END
        """
    )

    # Historical cleanup:
    # installment rows were auto-generated by periodic tasks even when members
    # had not opted into installment billing. Remove those rows and reset the
    # derived installment counters/state on affected enrollments.
    op.execute(
        """
        WITH affected AS (
            SELECT DISTINCT enrollment_id
            FROM enrollment_installments
        )
        UPDATE enrollments e
        SET
            uses_installments = false,
            total_installments = 0,
            paid_installments_count = 0,
            missed_installments_count = 0,
            access_suspended = false,
            payment_status = CASE
                WHEN e.paid_at IS NOT NULL OR e.payment_reference IS NOT NULL
                    THEN 'paid'::academy_payment_status_enum
                WHEN e.payment_status = 'failed'::academy_payment_status_enum
                    THEN 'pending'::academy_payment_status_enum
                ELSE e.payment_status
            END,
            status = CASE
                WHEN e.status IN (
                    'dropout_pending'::enrollment_status_enum,
                    'dropped'::enrollment_status_enum
                )
                AND (e.paid_at IS NOT NULL OR e.payment_reference IS NOT NULL)
                    THEN 'enrolled'::enrollment_status_enum
                ELSE e.status
            END
        WHERE e.id IN (SELECT enrollment_id FROM affected)
        """
    )

    op.execute(
        """
        DELETE FROM enrollment_installments
        """
    )


def downgrade() -> None:
    op.execute(
        """
        UPDATE programs
        SET price_amount = price_amount / 100
        """
    )
    op.execute(
        """
        UPDATE cohorts
        SET
            price_override = CASE
                WHEN price_override IS NULL THEN NULL
                ELSE price_override / 100
            END,
            installment_deposit_amount = CASE
                WHEN installment_deposit_amount IS NULL THEN NULL
                ELSE installment_deposit_amount / 100
            END
        """
    )
    op.execute(
        """
        UPDATE enrollments
        SET price_snapshot_amount = CASE
            WHEN price_snapshot_amount IS NULL THEN NULL
            ELSE price_snapshot_amount / 100
        END
        """
    )
    op.drop_column("enrollments", "uses_installments")
