"""Drop URL columns use media_id

Revision ID: fbde21296114
Revises: 4f2500bba144
Create Date: 2026-01-09 04:58:47.965384
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbde21296114'
down_revision = '4f2500bba144'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum_lessons', 'video_url')
    op.drop_column('milestones', 'video_url')
    op.drop_column('programs', 'cover_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('cover_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('curriculum_lessons', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
