"""add_volunteer_templates_and_sessiontemplate_slots

Revision ID: 18f8804a6300
Revises: 43c55eef83d6
Create Date: 2026-05-20 18:14:46.190698
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f8804a6300'
down_revision = '43c55eef83d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_template_volunteer_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_template_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('slots_needed', sa.Integer(), server_default='1', nullable=False),
    sa.Column('opportunity_type', sa.Enum('open_claim', 'approval_required', name='opportunity_type'), nullable=False),
    sa.Column('min_tier', sa.Enum('tier_1', 'tier_2', 'tier_3', name='volunteer_tier'), nullable=False),
    sa.Column('qr_checkin_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('title_override', sa.String(length=200), nullable=True),
    sa.Column('description_override', sa.Text(), nullable=True),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_template_volunteer_slots_role_id'), 'session_template_volunteer_slots', ['role_id'], unique=False)
    op.create_index(op.f('ix_session_template_volunteer_slots_session_template_id'), 'session_template_volunteer_slots', ['session_template_id'], unique=False)
    op.create_table('volunteer_opportunity_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('slots_needed', sa.Integer(), server_default='1', nullable=False),
    sa.Column('opportunity_type', sa.Enum('open_claim', 'approval_required', name='opportunity_type'), nullable=False),
    sa.Column('min_tier', sa.Enum('tier_1', 'tier_2', 'tier_3', name='volunteer_tier'), nullable=False),
    sa.Column('qr_checkin_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('auto_generate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_materialised_through', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_opportunity_templates_role_id'), 'volunteer_opportunity_templates', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_opportunity_templates_role_id'), table_name='volunteer_opportunity_templates')
    op.drop_table('volunteer_opportunity_templates')
    op.drop_index(op.f('ix_session_template_volunteer_slots_session_template_id'), table_name='session_template_volunteer_slots')
    op.drop_index(op.f('ix_session_template_volunteer_slots_role_id'), table_name='session_template_volunteer_slots')
    op.drop_table('session_template_volunteer_slots')
    # ### end Alembic commands ###
