"""add_qr_checkin_fields_to_opportunity

Revision ID: 8a840b164e5f
Revises: f1a2b3c4d901
Create Date: 2026-03-17 03:21:55.244537
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a840b164e5f'
down_revision = 'f1a2b3c4d901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_opportunities', sa.Column('qr_checkin_enabled', sa.Boolean(), nullable=False))
    op.add_column('volunteer_opportunities', sa.Column('qr_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_volunteer_opportunities_qr_token'), 'volunteer_opportunities', ['qr_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_opportunities_qr_token'), table_name='volunteer_opportunities')
    op.drop_column('volunteer_opportunities', 'qr_token')
    op.drop_column('volunteer_opportunities', 'qr_checkin_enabled')
    # ### end Alembic commands ###
