"""add_spotlight_fields_to_volunteer_profiles

Revision ID: 9f76cdd565e3
Revises: c7f2b54d3ec8
Create Date: 2026-02-08 14:35:36.662309
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f76cdd565e3'
down_revision = 'c7f2b54d3ec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_profiles', sa.Column('spotlight_quote', sa.Text(), nullable=True))
    op.add_column('volunteer_profiles', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('volunteer_profiles', sa.Column('featured_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('volunteer_profiles', sa.Column('featured_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_volunteer_profiles_is_featured'), 'volunteer_profiles', ['is_featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_profiles_is_featured'), table_name='volunteer_profiles')
    op.drop_column('volunteer_profiles', 'featured_until')
    op.drop_column('volunteer_profiles', 'featured_from')
    op.drop_column('volunteer_profiles', 'is_featured')
    op.drop_column('volunteer_profiles', 'spotlight_quote')
    # ### end Alembic commands ###
