"""initial_volunteer_tables

Revision ID: c7f2b54d3ec8
Revises: 
Create Date: 2026-02-08 03:34:24.828295
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7f2b54d3ec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('SESSION_LEAD', 'WARMUP_LEAD', 'LANE_MARSHAL', 'CHECKIN', 'SAFETY', 'WELCOME', 'RIDE_SHARE', 'MENTOR', 'MEDIA', 'GALLERY_SUPPORT', 'EVENTS_LOGISTICS', 'TRIP_PLANNER', 'ACADEMY_ASSISTANT', 'OTHER', name='volunteer_role_category'), nullable=False),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('min_tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='volunteer_tier'), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('volunteer_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('slots_needed', sa.Integer(), nullable=False),
    sa.Column('slots_filled', sa.Integer(), nullable=False),
    sa.Column('opportunity_type', sa.Enum('OPEN_CLAIM', 'APPROVAL_REQUIRED', name='opportunity_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'FILLED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='opportunity_status'), nullable=False),
    sa.Column('min_tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='volunteer_tier'), nullable=False),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_opportunities_date'), 'volunteer_opportunities', ['date'], unique=False)
    op.create_index(op.f('ix_volunteer_opportunities_role_id'), 'volunteer_opportunities', ['role_id'], unique=False)
    op.create_table('volunteer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='volunteer_tier'), nullable=False),
    sa.Column('tier_override', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='volunteer_tier'), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('total_sessions_volunteered', sa.Integer(), nullable=False),
    sa.Column('total_no_shows', sa.Integer(), nullable=False),
    sa.Column('total_late_cancellations', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.Column('recognition_tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', name='recognition_tier'), nullable=True),
    sa.Column('preferred_roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('available_days', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_profiles_member_id'), 'volunteer_profiles', ['member_id'], unique=True)
    op.create_table('volunteer_rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('reward_type', sa.Enum('DISCOUNTED_SESSION', 'FREE_MERCH', 'PRIORITY_EVENT', 'MEMBERSHIP_DISCOUNT', 'CUSTOM', name='reward_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_value', sa.String(length=100), nullable=True),
    sa.Column('is_redeemed', sa.Boolean(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('discount_amount_ngn', sa.Integer(), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_rewards_member_id'), 'volunteer_rewards', ['member_id'], unique=False)
    op.create_table('volunteer_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CLAIMED', 'APPROVED', 'REJECTED', 'CANCELLED', 'NO_SHOW', 'COMPLETED', name='slot_status'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours_logged', sa.Float(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('member_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['volunteer_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_slots_member_id'), 'volunteer_slots', ['member_id'], unique=False)
    op.create_index(op.f('ix_volunteer_slots_opportunity_id'), 'volunteer_slots', ['opportunity_id'], unique=False)
    op.create_table('volunteer_hours_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('logged_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['volunteer_opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['volunteer_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_hours_log_date'), 'volunteer_hours_log', ['date'], unique=False)
    op.create_index(op.f('ix_volunteer_hours_log_member_id'), 'volunteer_hours_log', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_hours_log_member_id'), table_name='volunteer_hours_log')
    op.drop_index(op.f('ix_volunteer_hours_log_date'), table_name='volunteer_hours_log')
    op.drop_table('volunteer_hours_log')
    op.drop_index(op.f('ix_volunteer_slots_opportunity_id'), table_name='volunteer_slots')
    op.drop_index(op.f('ix_volunteer_slots_member_id'), table_name='volunteer_slots')
    op.drop_table('volunteer_slots')
    op.drop_index(op.f('ix_volunteer_rewards_member_id'), table_name='volunteer_rewards')
    op.drop_table('volunteer_rewards')
    op.drop_index(op.f('ix_volunteer_profiles_member_id'), table_name='volunteer_profiles')
    op.drop_table('volunteer_profiles')
    op.drop_index(op.f('ix_volunteer_opportunities_role_id'), table_name='volunteer_opportunities')
    op.drop_index(op.f('ix_volunteer_opportunities_date'), table_name='volunteer_opportunities')
    op.drop_table('volunteer_opportunities')
    op.drop_table('volunteer_roles')
    # ### end Alembic commands ###
