"""Alembic script template for pools service."""

revision = "0d83071ddcd2"
down_revision = 'e6ab946fd81e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # Reuse the existing pool_partnership_status_enum (created by the initial
    # pools migration). postgresql.ENUM with create_type=False is the only
    # way sqlalchemy will skip CREATE TYPE inside create_table.
    partnership_status_enum = postgresql.ENUM(
        'prospect', 'evaluating', 'active_partner', 'inactive', 'rejected',
        name='pool_partnership_status_enum',
        create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'expired', 'terminated', name='pool_agreement_status_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('flat_session_rate_ngn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_sessions_per_month', sa.Integer(), nullable=True),
    sa.Column('is_exclusive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('signed_doc_media_id', sa.UUID(), nullable=True),
    sa.Column('signed_doc_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_agreements_pool_id'), 'pool_agreements', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_agreements_status'), 'pool_agreements', ['status'], unique=False)
    op.create_table('pool_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('photo', 'document', 'video', 'certificate', 'other', name='pool_asset_type_enum'), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uploaded_by_auth_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_assets_pool_id'), 'pool_assets', ['pool_id'], unique=False)
    op.create_table('pool_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'front_desk', 'accountant', 'operations', 'marketing', 'other', name='pool_contact_role_enum'), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_contacts_pool_id'), 'pool_contacts', ['pool_id'], unique=False)
    op.create_table('pool_status_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('from_status', partnership_status_enum, nullable=True),
    sa.Column('to_status', partnership_status_enum, nullable=False),
    sa.Column('changed_by_auth_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_status_changes_changed_by_auth_id'), 'pool_status_changes', ['changed_by_auth_id'], unique=False)
    op.create_index(op.f('ix_pool_status_changes_created_at'), 'pool_status_changes', ['created_at'], unique=False)
    op.create_index(op.f('ix_pool_status_changes_pool_id'), 'pool_status_changes', ['pool_id'], unique=False)
    op.create_table('pool_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('visit_type', sa.Enum('scouting', 'evaluation', 'partnership_meeting', 'session_check', 'incident', 'other', name='pool_visit_type_enum'), nullable=False),
    sa.Column('visitor_auth_id', sa.String(length=255), nullable=True),
    sa.Column('visitor_display_name', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_action', sa.Text(), nullable=True),
    sa.Column('follow_up_due_at', sa.Date(), nullable=True),
    sa.Column('follow_up_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_visits_pool_id'), 'pool_visits', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_visits_visit_date'), 'pool_visits', ['visit_date'], unique=False)
    op.create_index(op.f('ix_pool_visits_visitor_auth_id'), 'pool_visits', ['visitor_auth_id'], unique=False)
    op.add_column('pools', sa.Column('lifeguard_count', sa.Integer(), nullable=True))
    op.add_column('pools', sa.Column('has_first_aid_kit', sa.Boolean(), nullable=True))
    op.add_column('pools', sa.Column('has_aed', sa.Boolean(), nullable=True))
    op.add_column('pools', sa.Column('has_cctv', sa.Boolean(), nullable=True))
    op.add_column('pools', sa.Column('booking_lead_time_hours', sa.Integer(), nullable=True))

    # op.add_column does NOT auto-create enum types (unlike op.create_table).
    # Create the two net-new enums explicitly before adding their columns,
    # then reference them with create_type=False so sqlalchemy doesn't try
    # to create them again.
    preferred_contact_channel_enum = postgresql.ENUM(
        'whatsapp', 'phone', 'email', 'in_person',
        name='pool_preferred_contact_channel_enum',
        create_type=False,
    )
    source_enum = postgresql.ENUM(
        'member_submission', 'team_scouting', 'referral', 'direct_outreach', 'other',
        name='pool_source_enum',
        create_type=False,
    )
    preferred_contact_channel_enum.create(op.get_bind(), checkfirst=True)
    source_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('pools', sa.Column('preferred_contact_channel', preferred_contact_channel_enum, nullable=True))
    op.add_column('pools', sa.Column('source', source_enum, nullable=True))
    op.add_column('pools', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pools', 'last_verified_at')
    op.drop_column('pools', 'source')
    op.drop_column('pools', 'preferred_contact_channel')
    op.drop_column('pools', 'booking_lead_time_hours')
    op.drop_column('pools', 'has_cctv')
    op.drop_column('pools', 'has_aed')
    op.drop_column('pools', 'has_first_aid_kit')
    op.drop_column('pools', 'lifeguard_count')
    op.drop_index(op.f('ix_pool_visits_visitor_auth_id'), table_name='pool_visits')
    op.drop_index(op.f('ix_pool_visits_visit_date'), table_name='pool_visits')
    op.drop_index(op.f('ix_pool_visits_pool_id'), table_name='pool_visits')
    op.drop_table('pool_visits')
    op.drop_index(op.f('ix_pool_status_changes_pool_id'), table_name='pool_status_changes')
    op.drop_index(op.f('ix_pool_status_changes_created_at'), table_name='pool_status_changes')
    op.drop_index(op.f('ix_pool_status_changes_changed_by_auth_id'), table_name='pool_status_changes')
    op.drop_table('pool_status_changes')
    op.drop_index(op.f('ix_pool_contacts_pool_id'), table_name='pool_contacts')
    op.drop_table('pool_contacts')
    op.drop_index(op.f('ix_pool_assets_pool_id'), table_name='pool_assets')
    op.drop_table('pool_assets')
    op.drop_index(op.f('ix_pool_agreements_status'), table_name='pool_agreements')
    op.drop_index(op.f('ix_pool_agreements_pool_id'), table_name='pool_agreements')
    op.drop_table('pool_agreements')

    # Drop enum types created by this migration (pool_partnership_status_enum
    # is owned by the pools table and is NOT dropped here).
    op.execute("DROP TYPE IF EXISTS pool_source_enum")
    op.execute("DROP TYPE IF EXISTS pool_preferred_contact_channel_enum")
    op.execute("DROP TYPE IF EXISTS pool_visit_type_enum")
    op.execute("DROP TYPE IF EXISTS pool_contact_role_enum")
    op.execute("DROP TYPE IF EXISTS pool_asset_type_enum")
    op.execute("DROP TYPE IF EXISTS pool_agreement_status_enum")
    # ### end Alembic commands ###
