"""Alembic script template for pools service."""

revision = "49800070bb20"
down_revision = 'ca41d15dec17'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_key', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), server_default='open-meteo', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Africa/Lagos', nullable=False),
    sa.Column('forecast_days', sa.Integer(), server_default='14', nullable=False),
    sa.Column('hourly', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_fetched_at'), 'weather_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_location_key'), 'weather_snapshots', ['location_key'], unique=True)
    op.create_index(op.f('ix_weather_snapshots_pool_id'), 'weather_snapshots', ['pool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_snapshots_pool_id'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_location_key'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_fetched_at'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    # ### end Alembic commands ###
