"""Alembic script template for pools service."""

revision = "e6ab946fd81e"
down_revision = '9dfb808ce7a0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # Reuse the existing pool_type_enum (created by the initial pools migration).
    # Using postgresql.ENUM with create_type=False is the only way sqlalchemy
    # will skip the CREATE TYPE statement inside create_table — sa.Enum ignores it.
    pool_type_enum = postgresql.ENUM(
        'community', 'club', 'academy', 'private', 'public', 'hotel',
        name='pool_type_enum',
        create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submitter_auth_id', sa.String(length=255), nullable=False),
    sa.Column('submitter_display_name', sa.String(length=255), nullable=True),
    sa.Column('submitter_email', sa.String(length=255), nullable=True),
    sa.Column('pool_name', sa.String(length=255), nullable=False),
    sa.Column('location_area', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pool_type', pool_type_enum, nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('has_changing_rooms', sa.Boolean(), nullable=True),
    sa.Column('has_showers', sa.Boolean(), nullable=True),
    sa.Column('has_lockers', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('has_lifeguard', sa.Boolean(), nullable=True),
    sa.Column('visit_frequency', sa.String(length=50), nullable=True),
    sa.Column('member_rating', sa.Integer(), nullable=True),
    sa.Column('member_notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='pool_submission_status_enum'), server_default='pending', nullable=False),
    sa.Column('reviewed_by_auth_id', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('promoted_pool_id', sa.UUID(), nullable=True),
    sa.Column('reward_granted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reward_bubbles', sa.Integer(), nullable=True),
    sa.Column('reward_grant_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_submissions_status'), 'pool_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_pool_submissions_submitter_auth_id'), 'pool_submissions', ['submitter_auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pool_submissions_submitter_auth_id'), table_name='pool_submissions')
    op.drop_index(op.f('ix_pool_submissions_status'), table_name='pool_submissions')
    op.drop_table('pool_submissions')
    # Drop the enum type created by this migration (pool_type_enum is owned by the pools table).
    op.execute("DROP TYPE IF EXISTS pool_submission_status_enum")
    # ### end Alembic commands ###
