"""Alembic script template for store service."""

revision = "125217ac309e"
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('product', 'inventory', 'order', 'store_credit', 'category', 'pickup_location', name='store_audit_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_audit_logs_entity', 'store_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_store_audit_logs_performed_at', 'store_audit_logs', ['performed_at'], unique=False)
    op.create_table('store_carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_auth_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('discount_code', sa.String(length=50), nullable=True),
    sa.Column('member_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'converted', 'abandoned', 'expired', name='store_cart_status_enum'), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('member_auth_id IS NOT NULL OR session_id IS NOT NULL', name='cart_one_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_carts_member_auth_id'), 'store_carts', ['member_auth_id'], unique=False)
    op.create_index('ix_store_carts_member_auth_id_status', 'store_carts', ['member_auth_id', 'status'], unique=False)
    op.create_index(op.f('ix_store_carts_session_id'), 'store_carts', ['session_id'], unique=False)
    op.create_table('store_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_media_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['store_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('store_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_media_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('store_pickup_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('member_auth_id', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('subtotal_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount_ngn', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('store_credit_applied_ngn', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('delivery_fee_ngn', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_code', sa.String(length=50), nullable=True),
    sa.Column('discount_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending_payment', 'paid', 'processing', 'ready_for_pickup', 'picked_up', 'shipped', 'delivered', 'cancelled', 'refunded', 'payment_failed', name='store_order_status_enum'), server_default='pending_payment', nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('fulfillment_type', sa.Enum('pickup', 'delivery', name='store_fulfillment_type_enum'), server_default='pickup', nullable=False),
    sa.Column('pickup_location_id', sa.UUID(), nullable=True),
    sa.Column('pickup_session_id', sa.UUID(), nullable=True),
    sa.Column('delivery_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['store_pickup_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_orders_member_auth_id'), 'store_orders', ['member_auth_id'], unique=False)
    op.create_index(op.f('ix_store_orders_order_number'), 'store_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_store_orders_payment_reference'), 'store_orders', ['payment_reference'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('base_price_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_at_price_ngn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='store_product_status_enum'), server_default='draft', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('has_variants', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('variant_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sourcing_type', sa.Enum('stocked', 'preorder', name='store_sourcing_type_enum'), server_default='stocked', nullable=False),
    sa.Column('preorder_lead_days', sa.Integer(), nullable=True),
    sa.Column('requires_size_chart_ack', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('size_chart_media_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['store_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('store_collection_products',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['store_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'product_id')
    )
    op.create_table('store_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_auth_id', sa.String(length=255), nullable=False),
    sa.Column('amount_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('return', 'goodwill', 'promotion', 'admin', name='store_credit_source_type_enum'), nullable=False),
    sa.Column('source_order_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_order_id'], ['store_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_credits_member_auth_id'), 'store_credits', ['member_auth_id'], unique=False)
    op.create_table('store_product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_override_ngn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('store_cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='positive_quantity'),
    sa.ForeignKeyConstraint(['cart_id'], ['store_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['store_product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'variant_id', name='unique_cart_variant')
    )
    op.create_table('store_credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_credit_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['store_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_credit_id'], ['store_credits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), server_default='5', nullable=False),
    sa.Column('last_restock_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='positive_stock'),
    sa.CheckConstraint('quantity_reserved >= 0 AND quantity_reserved <= quantity_on_hand', name='valid_reserved'),
    sa.ForeignKeyConstraint(['variant_id'], ['store_product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id')
    )
    op.create_table('store_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_preorder', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('estimated_ship_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['store_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['store_product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['store_product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('restock', 'sale', 'reservation', 'release', 'adjustment', 'return', name='store_inventory_movement_type_enum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['store_inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_inventory_movements')
    op.drop_table('store_product_images')
    op.drop_table('store_order_items')
    op.drop_table('store_inventory_items')
    op.drop_table('store_credit_transactions')
    op.drop_table('store_cart_items')
    op.drop_table('store_product_variants')
    op.drop_index(op.f('ix_store_credits_member_auth_id'), table_name='store_credits')
    op.drop_table('store_credits')
    op.drop_table('store_collection_products')
    op.drop_table('store_products')
    op.drop_index(op.f('ix_store_orders_payment_reference'), table_name='store_orders')
    op.drop_index(op.f('ix_store_orders_order_number'), table_name='store_orders')
    op.drop_index(op.f('ix_store_orders_member_auth_id'), table_name='store_orders')
    op.drop_table('store_orders')
    op.drop_table('store_pickup_locations')
    op.drop_table('store_collections')
    op.drop_table('store_categories')
    op.drop_index(op.f('ix_store_carts_session_id'), table_name='store_carts')
    op.drop_index('ix_store_carts_member_auth_id_status', table_name='store_carts')
    op.drop_index(op.f('ix_store_carts_member_auth_id'), table_name='store_carts')
    op.drop_table('store_carts')
    op.drop_index('ix_store_audit_logs_performed_at', table_name='store_audit_logs')
    op.drop_index('ix_store_audit_logs_entity', table_name='store_audit_logs')
    op.drop_table('store_audit_logs')
    # ### end Alembic commands ###
