"""Alembic script template for store service."""

revision = "19aaf8659c98"
down_revision = 'fb276644654d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_categories', 'image_url')
    op.drop_column('store_collections', 'image_url')
    op.drop_column('store_products', 'size_chart_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_products', sa.Column('size_chart_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('store_collections', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('store_categories', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
