"""Alembic script template for store service."""

revision = "1f6cd588faf9"
down_revision = 'cbeff7473ac0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_bundle_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bundle_product_id', sa.UUID(), nullable=False),
    sa.Column('component_product_id', sa.UUID(), nullable=False),
    sa.Column('component_variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bundle_product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_variant_id'], ['store_product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Bundle/kit component items'
    )
    op.create_index(op.f('ix_store_bundle_items_bundle_product_id'), 'store_bundle_items', ['bundle_product_id'], unique=False)
    op.create_index(op.f('ix_store_bundle_items_component_product_id'), 'store_bundle_items', ['component_product_id'], unique=False)
    store_product_type_enum = sa.Enum('standard', 'bundle', name='store_product_type_enum')
    store_product_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('store_products', sa.Column('product_type', store_product_type_enum, server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_products', 'product_type')
    sa.Enum(name='store_product_type_enum').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_store_bundle_items_component_product_id'), table_name='store_bundle_items')
    op.drop_index(op.f('ix_store_bundle_items_bundle_product_id'), table_name='store_bundle_items')
    op.drop_table('store_bundle_items')
    # ### end Alembic commands ###
