"""Alembic script template for store service."""

revision = "3cb5a77a69fe"
down_revision = 'ad15e706a57a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payout_bank_name', sa.String(length=255), nullable=True),
    sa.Column('payout_account_number', sa.String(length=50), nullable=True),
    sa.Column('payout_account_name', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('active', 'probation', 'suspended', 'inactive', name='store_supplier_status_enum'), server_default='active', nullable=False),
    sa.Column('probation_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_products', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('average_fulfillment_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('store_supplier_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('payout_period_start', sa.Date(), nullable=False),
    sa.Column('payout_period_end', sa.Date(), nullable=False),
    sa.Column('total_sales_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payout_amount_ngn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'failed', name='store_payout_status_enum'), server_default='pending', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['store_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_supplier_payouts_supplier_id'), 'store_supplier_payouts', ['supplier_id'], unique=False)
    op.add_column('store_order_items', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.add_column('store_order_items', sa.Column('supplier_name', sa.String(length=255), nullable=True))
    op.add_column('store_pickup_locations', sa.Column('pool_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_store_pickup_locations_pool_id'), 'store_pickup_locations', ['pool_id'], unique=False)
    op.add_column('store_products', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.add_column('store_products', sa.Column('cost_price_ngn', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index(op.f('ix_store_products_supplier_id'), 'store_products', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'store_products', 'store_suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_products', type_='foreignkey')
    op.drop_index(op.f('ix_store_products_supplier_id'), table_name='store_products')
    op.drop_column('store_products', 'cost_price_ngn')
    op.drop_column('store_products', 'supplier_id')
    op.drop_index(op.f('ix_store_pickup_locations_pool_id'), table_name='store_pickup_locations')
    op.drop_column('store_pickup_locations', 'pool_id')
    op.drop_column('store_order_items', 'supplier_name')
    op.drop_column('store_order_items', 'supplier_id')
    op.drop_index(op.f('ix_store_supplier_payouts_supplier_id'), table_name='store_supplier_payouts')
    op.drop_table('store_supplier_payouts')
    op.drop_table('store_suppliers')
    # ### end Alembic commands ###
