"""B4 audit canonical shape: stage 1 — add new columns (nullable).

Stage 1 of two for store_audit_logs adopting `libs.common.audit.AuditLogMixin`.

This stage is purely **additive**: it adds the canonical columns as
NULLABLE so existing rows remain valid. Stage 2
(``5db2653c9ce8_b4_audit_canonical_shape_backfill_and_.py``) backfills,
flips NOT NULL, converts ``entity_type`` enum→String, and drops the
legacy ``performed_at`` / ``performed_by`` / ``notes`` columns.

The original autogenerated body included the destructive operations
(drop columns, enum→string convert, NOT NULL on new columns) in this
stage. Those were moved to stage 2 so this migration is a safe rollback
boundary: if stage 2 fails or needs to be reverted, the old columns and
old indexes still exist with their data intact.

The new indexes (`ix_store_audit_entity_created`,
`ix_store_audit_created_at`) ARE created here because they don't depend
on the backfilled data — they sit on `entity_id` (existing) and
`created_at` (added here, NULLABLE for now). The old indexes are kept
in place until stage 2.
"""

revision = "7ff40e02772d"
down_revision = '1f6cd588faf9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ── Additive: new canonical columns, all nullable ────────────────
    # Stage 2 will populate them from existing rows then ALTER NOT NULL.
    op.add_column(
        'store_audit_logs',
        sa.Column('domain', sa.String(length=32), nullable=True),
    )
    op.add_column(
        'store_audit_logs',
        sa.Column('actor_id', sa.UUID(), nullable=True),
    )
    op.add_column(
        'store_audit_logs',
        sa.Column('actor_label', sa.String(length=255), nullable=True),
    )
    op.add_column(
        'store_audit_logs',
        sa.Column('reason', sa.String(), nullable=True),
    )
    op.add_column(
        'store_audit_logs',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    # ── New indexes on canonical columns ─────────────────────────────
    # Safe to create now: entity_id already existed; created_at is
    # added above. Old indexes (ix_store_audit_logs_entity / _performed_at)
    # remain in place until stage 2 drops them along with their columns.
    op.create_index(
        'ix_store_audit_entity_created',
        'store_audit_logs',
        ['entity_id', 'created_at'],
        unique=False,
    )
    op.create_index(
        'ix_store_audit_created_at',
        'store_audit_logs',
        ['created_at'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index('ix_store_audit_created_at', table_name='store_audit_logs')
    op.drop_index('ix_store_audit_entity_created', table_name='store_audit_logs')
    op.drop_column('store_audit_logs', 'created_at')
    op.drop_column('store_audit_logs', 'reason')
    op.drop_column('store_audit_logs', 'actor_label')
    op.drop_column('store_audit_logs', 'actor_id')
    op.drop_column('store_audit_logs', 'domain')
