"""Alembic script template for store service."""

revision = "ad15e706a57a"
down_revision = '6ca976db4946'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_orders', sa.Column('bubbles_applied', sa.Integer(), nullable=True))
    op.add_column('store_orders', sa.Column('wallet_transaction_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_store_orders_wallet_transaction_id'), 'store_orders', ['wallet_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_orders_wallet_transaction_id'), table_name='store_orders')
    op.drop_column('store_orders', 'wallet_transaction_id')
    op.drop_column('store_orders', 'bubbles_applied')
    # ### end Alembic commands ###
