"""Alembic script template for store service."""

revision = "fb276644654d"
down_revision = 'd63a416ef1f6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_categories', sa.Column('image_media_id', sa.UUID(), nullable=True))
    op.add_column('store_collections', sa.Column('image_media_id', sa.UUID(), nullable=True))
    op.add_column('store_products', sa.Column('size_chart_media_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_products', 'size_chart_media_id')
    op.drop_column('store_collections', 'image_media_id')
    op.drop_column('store_categories', 'image_media_id')
    # ### end Alembic commands ###
