"""add_wallet_transaction_id_to_event_rsvps

Revision ID: 8fe705900f75
Revises: d99bdcfade1e
Create Date: 2026-02-27 04:28:50.848082
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe705900f75'
down_revision = 'd99bdcfade1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_rsvps', sa.Column('wallet_transaction_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_rsvps', 'wallet_transaction_id')
    # ### end Alembic commands ###
