"""add_cost_kobo_to_events

Revision ID: d99bdcfade1e
Revises: 120e263e86d0
Create Date: 2026-02-24 16:31:30.416690
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99bdcfade1e'
down_revision = '120e263e86d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('cost_kobo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'cost_kobo')
    # ### end Alembic commands ###
