"""add_open_swim_pool_fields_to_events

Revision ID: e37ec62e2cff
Revises: 8fe705900f75
Create Date: 2026-06-24 09:14:40.547182
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37ec62e2cff'
down_revision = '8fe705900f75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('pool_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('pool_fee_kobo', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('organizer_surcharge_kobo', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'organizer_surcharge_kobo')
    op.drop_column('events', 'pool_fee_kobo')
    op.drop_column('events', 'pool_id')
    # ### end Alembic commands ###
