"""add_audio_tracks

Revision ID: 35f4a6b1f40e
Revises: 88d53e5ef18b
Create Date: 2026-03-10 04:07:56.534669
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f4a6b1f40e'
down_revision = '88d53e5ef18b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('license_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_tracks')
    # ### end Alembic commands ###
