"""Backfill guest admission and add guest policy constraints.

Revision ID: 0437991503dd
Revises: dac9b92b1158
Create Date: 2026-09-23

Hand-written migration — Alembic cannot infer data backfills or changes to
CHECK constraints. The schema additions are autogenerated in dac9b92b1158.
Only explicitly priced Club/Community guest sessions keep public access.
Academy and Event sessions require an administrator's deliberate opt-in.
"""
from alembic import op

revision = "0437991503dd"
down_revision = "dac9b92b1158"
branch_labels = None
depends_on = None


CHECKS = [
    ("sessions", "ck_sessions_guest_booking_mode", "guest_booking_mode IN ('disabled','public','member_invite','approval_required')"),
    ("sessions", "ck_sessions_guest_reconciliation_days", "guest_reconciliation_days BETWEEN 0 AND 30"),
    ("sessions", "ck_sessions_guest_fee_nonnegative", "guest_fee_kobo IS NULL OR guest_fee_kobo >= 0"),
    ("guest_passes", "ck_guest_pass_booking_mode", "booking_mode IN ('reservation','settlement')"),
]


def upgrade() -> None:
    op.execute("""UPDATE sessions SET guest_booking_mode = 'public'
        WHERE allows_guests = true AND guest_fee_kobo IS NOT NULL
        AND guest_fee_kobo >= 0 AND session_type IN ('club', 'community')""")
    # Existing payment methods belong to Payments; do not guess or overwrite
    # them from the new default. This is a migration-only cross-service join.
    op.execute("""DO $$ BEGIN
        IF to_regclass('public.payments') IS NOT NULL THEN
            UPDATE guest_passes AS guest SET payment_method = payment.payment_method
            FROM payments AS payment WHERE payment.reference = guest.payment_reference
            AND payment.payment_method IN ('paystack', 'manual_transfer');
        END IF;
    END $$""")
    # Historical acknowledgement text was not versioned. Leave its version
    # NULL rather than claiming the guest accepted the new version.
    for table, name, expression in CHECKS:
        op.create_check_constraint(name, table, expression)


def downgrade() -> None:
    for table, name, _expression in reversed(CHECKS):
        op.drop_constraint(name, table, type_="check")
    # Don't overwrite administrators' subsequent access choices on downgrade.
