"""add_pod_id_to_sessions_for_podscoped_club_sessions

Revision ID: 06035b9c5f02
Revises: 5ca7cf6e4ead
Create Date: 2026-05-10 17:07:15.548319
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06035b9c5f02'
down_revision = '5ca7cf6e4ead'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('pod_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sessions_pod_id'), 'sessions', ['pod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_pod_id'), table_name='sessions')
    op.drop_column('sessions', 'pod_id')
    # ### end Alembic commands ###
