"""add_makeup_bookings_completed_at

Revision ID: 0f370a4ff28d
Revises: 68eb970d1c1b
Create Date: 2026-06-05 07:12:22.217025
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f370a4ff28d'
down_revision = '68eb970d1c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('makeup_bookings', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('makeup_bookings', 'completed_at')
    # ### end Alembic commands ###
