"""add_makeup_requested_time_columns

Revision ID: 2a116b947232
Revises: 8427bdefbb24
Create Date: 2026-06-12 18:38:40.177885
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a116b947232'
down_revision = '8427bdefbb24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('makeup_bookings', sa.Column('requested_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('makeup_bookings', sa.Column('requested_end_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('makeup_bookings', 'requested_end_at')
    op.drop_column('makeup_bookings', 'requested_start_at')
    # ### end Alembic commands ###
