"""add_session_bookings_table

Revision ID: 342fc616217e
Revises: 0cfeb8c4ddfb
Create Date: 2026-05-17 10:05:56.989152
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342fc616217e'
down_revision = '0cfeb8c4ddfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('member_auth_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', name='session_booking_status_enum'), server_default='pending', nullable=False),
    sa.Column('channel', sa.Enum('member_self', 'admin', 'corporate_bulk', 'bundle_cart', name='booking_channel_enum'), server_default='member_self', nullable=False),
    sa.Column('fee_amount_kobo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=True),
    sa.Column('wallet_transaction_id', sa.UUID(), nullable=True),
    sa.Column('corporate_program_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'member_id', name='uq_session_bookings_session_member')
    )
    op.create_index(op.f('ix_session_bookings_corporate_program_id'), 'session_bookings', ['corporate_program_id'], unique=False)
    op.create_index(op.f('ix_session_bookings_member_auth_id'), 'session_bookings', ['member_auth_id'], unique=False)
    op.create_index(op.f('ix_session_bookings_member_id'), 'session_bookings', ['member_id'], unique=False)
    op.create_index(op.f('ix_session_bookings_payment_intent_id'), 'session_bookings', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_session_bookings_session_id'), 'session_bookings', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_bookings_session_id'), table_name='session_bookings')
    op.drop_index(op.f('ix_session_bookings_payment_intent_id'), table_name='session_bookings')
    op.drop_index(op.f('ix_session_bookings_member_id'), table_name='session_bookings')
    op.drop_index(op.f('ix_session_bookings_member_auth_id'), table_name='session_bookings')
    op.drop_index(op.f('ix_session_bookings_corporate_program_id'), table_name='session_bookings')
    op.drop_table('session_bookings')
    # ### end Alembic commands ###
