"""add_draft_status_and_published_at_to_sessions

Revision ID: 66a7cc16dc78
Revises: 8dfce262cbc2
Create Date: 2026-02-09 14:25:01.159693
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a7cc16dc78'
down_revision = '8dfce262cbc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'published_at')
    # ### end Alembic commands ###
