"""add_makeup_bookings_table

Revision ID: 68eb970d1c1b
Revises: f4b1ce87bd66
Create Date: 2026-06-03 13:52:19.724274
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eb970d1c1b'
down_revision = 'f4b1ce87bd66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makeup_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_member_id', sa.UUID(), nullable=False),
    sa.Column('coach_member_id', sa.UUID(), nullable=False),
    sa.Column('learner_type', sa.Enum('cohort', 'one_on_one', name='makeup_booking_learner_type_enum'), server_default='cohort', nullable=False),
    sa.Column('block_kind', sa.Enum('cohort_term', 'lesson_package', name='makeup_booking_block_kind_enum'), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.Enum('learner_reschedule', 'excused_absence', 'session_cancelled', 'late_join', name='makeup_booking_origin_enum'), nullable=False),
    sa.Column('original_session_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'held', 'confirmed', 'completed', 'forfeited', 'expired', 'cancelled', name='makeup_booking_status_enum'), server_default='requested', nullable=False),
    sa.Column('used_grace', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notice_hours_at_request', sa.Integer(), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spacing_overridden_by', sa.UUID(), nullable=True),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_makeup_bookings_block_id'), 'makeup_bookings', ['block_id'], unique=False)
    op.create_index(op.f('ix_makeup_bookings_coach_member_id'), 'makeup_bookings', ['coach_member_id'], unique=False)
    op.create_index(op.f('ix_makeup_bookings_learner_member_id'), 'makeup_bookings', ['learner_member_id'], unique=False)
    op.create_index('ix_makeup_bookings_learner_status', 'makeup_bookings', ['learner_member_id', 'status'], unique=False)
    op.create_index(op.f('ix_makeup_bookings_obligation_id'), 'makeup_bookings', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_makeup_bookings_original_session_id'), 'makeup_bookings', ['original_session_id'], unique=False)
    op.create_index(op.f('ix_makeup_bookings_scheduled_session_id'), 'makeup_bookings', ['scheduled_session_id'], unique=False)
    op.create_index(op.f('ix_makeup_bookings_status'), 'makeup_bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_makeup_bookings_status'), table_name='makeup_bookings')
    op.drop_index(op.f('ix_makeup_bookings_scheduled_session_id'), table_name='makeup_bookings')
    op.drop_index(op.f('ix_makeup_bookings_original_session_id'), table_name='makeup_bookings')
    op.drop_index(op.f('ix_makeup_bookings_obligation_id'), table_name='makeup_bookings')
    op.drop_index('ix_makeup_bookings_learner_status', table_name='makeup_bookings')
    op.drop_index(op.f('ix_makeup_bookings_learner_member_id'), table_name='makeup_bookings')
    op.drop_index(op.f('ix_makeup_bookings_coach_member_id'), table_name='makeup_bookings')
    op.drop_index(op.f('ix_makeup_bookings_block_id'), table_name='makeup_bookings')
    op.drop_table('makeup_bookings')
    # ### end Alembic commands ###
