"""initial_migration

Revision ID: 690bb91cfa2d
Revises: 
Create Date: 2026-01-03 09:34:17.919119
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '690bb91cfa2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_type', sa.Enum('COHORT_CLASS', 'ONE_ON_ONE', 'GROUP_BOOKING', 'CLUB', 'COMMUNITY', 'EVENT', name='session_type_enum'), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='20', nullable=False),
    sa.Column('pool_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ride_share_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ride_share_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_generate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.Enum('COHORT_CLASS', 'ONE_ON_ONE', 'GROUP_BOOKING', 'CLUB', 'COMMUNITY', 'EVENT', name='session_type_enum'), server_default='CLUB', nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='session_status_enum'), server_default='SCHEDULED', nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), server_default='Africa/Lagos', nullable=False),
    sa.Column('location', sa.Enum('SUNFIT_POOL', 'ROWE_PARK_POOL', 'FEDERAL_PALACE_POOL', 'OPEN_WATER', 'OTHER', name='session_location_enum'), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), server_default='20', nullable=False),
    sa.Column('pool_fee', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('ride_share_fee', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('lesson_title', sa.String(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('is_recurring_instance', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['session_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_booking_id'), 'sessions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_sessions_cohort_id'), 'sessions', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_sessions_event_id'), 'sessions', ['event_id'], unique=False)
    op.create_table('session_coaches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), server_default='lead', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_coaches_coach_id'), 'session_coaches', ['coach_id'], unique=False)
    op.create_index(op.f('ix_session_coaches_session_id'), 'session_coaches', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_coaches_session_id'), table_name='session_coaches')
    op.drop_index(op.f('ix_session_coaches_coach_id'), table_name='session_coaches')
    op.drop_table('session_coaches')
    op.drop_index(op.f('ix_sessions_event_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_cohort_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_booking_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('session_templates')
    # ### end Alembic commands ###
