"""add_pods_and_pod_assignments

Revision ID: 7c13c1913395
Revises: b7393430eddd
Create Date: 2026-05-10 10:32:20.423555

Idempotency note (added 2026-05-10):
    In May 2026 pods moved out of sessions_service into members_service —
    see ``services/members_service/alembic/versions/a4d7086677ea_*.py`` and
    ``5ca7cf6e4ead_drop_pods_and_pod_assignments_moved_to_members_service.py``
    in this directory. Because reset/migration scripts apply
    members_service before sessions_service, by the time this migration
    runs in production (where it had never run before the move), the
    members_service migration has already created ``pods`` /
    ``pod_assignments`` and the related enums.

    The body below is wrapped in an idempotency guard: if ``pods``
    already exists, we treat the migration as a no-op so the alembic
    chain advances cleanly to ``5ca7cf6e4ead`` (the no-op marker that
    follows). In any environment where this migration legitimately
    needs to run (very-old dev branches that never picked up the
    members_service change), the original body still runs unchanged.
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c13c1913395"
down_revision = "b7393430eddd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── Idempotency guard ──────────────────────────────────────────
    # If members_service already created the pods table (in a4d7086677ea),
    # skip the entire body. See module docstring for full context.
    bind = op.get_bind()
    pods_already_exists = bind.execute(
        sa.text("SELECT to_regclass('public.pods')")
    ).scalar() is not None
    if pods_already_exists:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("club_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("lead_coach_id", sa.UUID(), nullable=False),
        sa.Column("assistant_coach_id", sa.UUID(), nullable=True),
        sa.Column("min_size", sa.Integer(), server_default="2", nullable=False),
        sa.Column("max_size", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="pod_visibility_enum"),
            server_default="public",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="pod_status_enum"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("cycle_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dissolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "slug", name="uq_pods_club_slug"),
    )
    op.create_index(op.f("ix_pods_club_id"), "pods", ["club_id"], unique=False)
    op.create_index("ix_pods_club_status", "pods", ["club_id", "status"], unique=False)
    op.create_index("ix_pods_directory", "pods", ["visibility", "status"], unique=False)
    op.create_index(
        op.f("ix_pods_lead_coach_id"), "pods", ["lead_coach_id"], unique=False
    )
    op.create_index("ix_pods_review_due", "pods", ["review_due_at"], unique=False)
    op.create_table(
        "pod_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pod_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "assigned_by",
            sa.Enum(
                "admin", "self", "coach_transfer", name="pod_assignment_source_enum"
            ),
            nullable=False,
        ),
        sa.Column("assigned_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["pod_id"], ["pods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pod_assignments_active_per_pod",
        "pod_assignments",
        ["pod_id"],
        unique=False,
        postgresql_where="left_at IS NULL",
    )
    op.create_index(
        op.f("ix_pod_assignments_member_id"),
        "pod_assignments",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        "uq_pod_assignments_one_active_per_member",
        "pod_assignments",
        ["member_id"],
        unique=True,
        postgresql_where="left_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_pod_assignments_one_active_per_member",
        table_name="pod_assignments",
        postgresql_where="left_at IS NULL",
    )
    op.drop_index(op.f("ix_pod_assignments_member_id"), table_name="pod_assignments")
    op.drop_index(
        "ix_pod_assignments_active_per_pod",
        table_name="pod_assignments",
        postgresql_where="left_at IS NULL",
    )
    op.drop_table("pod_assignments")
    op.drop_index("ix_pods_review_due", table_name="pods")
    op.drop_index(op.f("ix_pods_lead_coach_id"), table_name="pods")
    op.drop_index("ix_pods_directory", table_name="pods")
    op.drop_index("ix_pods_club_status", table_name="pods")
    op.drop_index(op.f("ix_pods_club_id"), table_name="pods")
    op.drop_table("pods")
    # ### end Alembic commands ###
