"""add_guest_booking_party_size_allows_guests_booking_guests

Revision ID: 8427bdefbb24
Revises: 0f370a4ff28d
Create Date: 2026-06-09 23:03:45.135229
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8427bdefbb24'
down_revision = '0f370a4ff28d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), server_default='social', nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('guardian_name', sa.Text(), nullable=True),
    sa.Column('guardian_phone', sa.Text(), nullable=True),
    sa.Column('waiver_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_member_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("intent IN ('social', 'trial')", name='ck_booking_guests_intent'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_guests_booking_id'), 'booking_guests', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_guests_phone'), 'booking_guests', ['phone'], unique=False)
    op.add_column('session_bookings', sa.Column('party_size', sa.Integer(), server_default='1', nullable=False))
    # Alembic autogenerate cannot represent a CHECK constraint added to an
    # existing table — add it explicitly so the DB matches the model
    # (ck_session_bookings_party_size in models/booking.py).
    op.create_check_constraint(
        'ck_session_bookings_party_size', 'session_bookings', 'party_size >= 1'
    )
    op.add_column('sessions', sa.Column('allows_guests', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('sessions', sa.Column('max_guests_per_booking', sa.Integer(), server_default='4', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'max_guests_per_booking')
    op.drop_column('sessions', 'allows_guests')
    op.drop_constraint('ck_session_bookings_party_size', 'session_bookings', type_='check')
    op.drop_column('session_bookings', 'party_size')
    op.drop_index(op.f('ix_booking_guests_phone'), table_name='booking_guests')
    op.drop_index(op.f('ix_booking_guests_booking_id'), table_name='booking_guests')
    op.drop_table('booking_guests')
    # ### end Alembic commands ###
