"""add_session_bundle_carts_table

Revision ID: 85f1b20d9f00
Revises: f10b53edfa38
Create Date: 2026-04-05 13:08:36.043318
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85f1b20d9f00'
down_revision = 'f10b53edfa38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_bundle_carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_auth_id', sa.String(), nullable=False),
    sa.Column('session_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_bundle_carts_member_auth_id'), 'session_bundle_carts', ['member_auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_bundle_carts_member_auth_id'), table_name='session_bundle_carts')
    op.drop_table('session_bundle_carts')
    # ### end Alembic commands ###
