"""add_pool_id_to_sessions

Revision ID: b7393430eddd
Revises: 85f1b20d9f00
Create Date: 2026-04-18 08:43:16.608019
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7393430eddd'
down_revision = '85f1b20d9f00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('pool_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sessions_pool_id'), 'sessions', ['pool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_pool_id'), table_name='sessions')
    op.drop_column('sessions', 'pool_id')
    # ### end Alembic commands ###
