"""Store confirmed payment totals for booking email retries

Revision ID: bd99897b8e40
Revises: 0437991503dd
Create Date: 2026-09-23 20:36:32.819410
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd99897b8e40'
down_revision = '0437991503dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_email_deliveries', sa.Column('payment_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_email_deliveries', 'payment_details')
    # ### end Alembic commands ###
