"""add_pool_id_and_location_name_to_session_templates

Revision ID: cca485ecbeb5
Revises: 06035b9c5f02
Create Date: 2026-05-15 15:39:26.665822
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca485ecbeb5'
down_revision = '06035b9c5f02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_templates', sa.Column('pool_id', sa.UUID(), nullable=True))
    op.add_column('session_templates', sa.Column('location_name', sa.String(), nullable=True))
    op.alter_column('session_templates', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_session_templates_pool_id'), 'session_templates', ['pool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_templates_pool_id'), table_name='session_templates')
    op.alter_column('session_templates', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('session_templates', 'location_name')
    op.drop_column('session_templates', 'pool_id')
    # ### end Alembic commands ###
