"""initial_migration

Revision ID: cddf7427020b
Revises: 
Create Date: 2025-12-31 00:11:25.413463
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cddf7427020b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CLUB', 'ACADEMY', 'COMMUNITY', name='session_type_enum'), nullable=False),
    sa.Column('pool_fee', sa.Integer(), nullable=False),
    sa.Column('ride_share_fee', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('ride_share_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_generate', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('CLUB', 'ACADEMY', 'COMMUNITY', name='session_type_enum'), nullable=False),
    sa.Column('location', sa.Enum('SUNFIT_POOL', 'ROWE_PARK_POOL', 'FEDERAL_PALACE_POOL', 'OPEN_WATER', name='session_location_enum'), nullable=False),
    sa.Column('pool_fee', sa.Float(), nullable=False),
    sa.Column('ride_share_fee', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('is_recurring_instance', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['session_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_cohort_id'), 'sessions', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_sessions_event_id'), 'sessions', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_event_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_cohort_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('session_templates')
    # ### end Alembic commands ###
