"""add guest admission lifecycle and confirmation outbox

Revision ID: dac9b92b1158
Revises: a9b1c3d5e748
Create Date: 2026-09-23 15:46:01.614629
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac9b92b1158'
down_revision = 'a9b1c3d5e748'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_email_deliveries',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_booking_email_deliveries_available_at'), 'booking_email_deliveries', ['available_at'], unique=False)
    op.create_table('guest_booking_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_by_pass_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_guest_booking_grants_session_id'), 'guest_booking_grants', ['session_id'], unique=False)
    op.create_table('guest_link_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('booking_source', sa.String(length=80), nullable=True),
    sa.Column('campaign_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_link_events_session_id'), 'guest_link_events', ['session_id'], unique=False)
    op.add_column('guest_passes', sa.Column('booking_mode', sa.String(length=24), server_default='reservation', nullable=False))
    op.add_column('guest_passes', sa.Column('booking_source', sa.String(length=80), nullable=True))
    op.add_column('guest_passes', sa.Column('campaign_key', sa.String(length=120), nullable=True))
    op.add_column('guest_passes', sa.Column('safety_acknowledgement_version', sa.String(length=40), nullable=True))
    op.add_column('guest_passes', sa.Column('confirmation_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('guest_passes', sa.Column('payment_method', sa.String(length=24), server_default='paystack', nullable=False))
    op.create_index(op.f('ix_guest_passes_campaign_key'), 'guest_passes', ['campaign_key'], unique=False)
    op.add_column('session_bookings', sa.Column('confirmation_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('guest_booking_mode', sa.String(length=24), server_default='disabled', nullable=False))
    op.add_column('sessions', sa.Column('guest_booking_closes_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('guest_reconciliation_days', sa.Integer(), server_default='3', nullable=False))
    op.add_column('sessions', sa.Column('guest_location_private', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'guest_location_private')
    op.drop_column('sessions', 'guest_reconciliation_days')
    op.drop_column('sessions', 'guest_booking_closes_at')
    op.drop_column('sessions', 'guest_booking_mode')
    op.drop_column('session_bookings', 'confirmation_email_sent_at')
    op.drop_index(op.f('ix_guest_passes_campaign_key'), table_name='guest_passes')
    op.drop_column('guest_passes', 'payment_method')
    op.drop_column('guest_passes', 'confirmation_email_sent_at')
    op.drop_column('guest_passes', 'safety_acknowledgement_version')
    op.drop_column('guest_passes', 'campaign_key')
    op.drop_column('guest_passes', 'booking_source')
    op.drop_column('guest_passes', 'booking_mode')
    op.drop_index(op.f('ix_guest_link_events_session_id'), table_name='guest_link_events')
    op.drop_table('guest_link_events')
    op.drop_index(op.f('ix_guest_booking_grants_session_id'), table_name='guest_booking_grants')
    op.drop_table('guest_booking_grants')
    op.drop_index(op.f('ix_booking_email_deliveries_available_at'), table_name='booking_email_deliveries')
    op.drop_table('booking_email_deliveries')
    # ### end Alembic commands ###
