"""convert_pool_fee_ride_share_fee_to_kobo_integer

Revision ID: f10b53edfa38
Revises: e1f2a3b4c801
Create Date: 2026-02-24 15:31:06.232107
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10b53edfa38'
down_revision = 'e1f2a3b4c801'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # postgresql_using converts existing naira float values → kobo integers (×100).
    # e.g. 2000.0 (₦2,000) → 200000 (200,000 kobo). Safe no-op on empty tables.
    op.alter_column('sessions', 'pool_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"),
               postgresql_using="ROUND(pool_fee * 100)::integer")
    op.alter_column('sessions', 'ride_share_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"),
               postgresql_using="ROUND(ride_share_fee * 100)::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse: kobo integers → naira floats (÷100).
    op.alter_column('sessions', 'ride_share_fee',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"),
               postgresql_using="(ride_share_fee / 100.0)::double precision")
    op.alter_column('sessions', 'pool_fee',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"),
               postgresql_using="(pool_fee / 100.0)::double precision")
    # ### end Alembic commands ###
